//*****************************************************************************
//
// enet_io.c - I/O control via a web server.
//
// Copyright (c) 2013-2020 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
// Texas Instruments (TI) is supplying this software for use solely and
// exclusively on TI's microcontroller products. The software is owned by
// TI and/or its suppliers, and is protected under applicable copyright
// laws. You may not combine this software with "viral" open-source
// software in order to form a larger program.
// 
// THIS SOFTWARE IS PROVIDED "AS IS" AND WITH ALL FAULTS.
// NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
// NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. TI SHALL NOT, UNDER ANY
// CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, FOR ANY REASON WHATSOEVER.
// 
// This is part of revision 2.2.0.295 of the EK-TM4C1294XL Firmware Package.
//
//*****************************************************************************

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_types.h"
#include "driverlib/flash.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "driverlib/timer.h"
#include "utils/locator.h"
#include "utils/lwiplib.h"
#include "third_party/lwip-1.4.1/src/include/lwip/netif.h"
#include "utils/uartstdio.h"
#include "utils/ustdlib.h"
#include "httpserver_raw/httpd.h"
#include "drivers/pinout.h"
#include "io.h"
#include "cgifuncs.h"
#include "config.h"
#include "mqtt_app.h"
#include "din_chain.h"
#include "relay_chain.h"
#include "input_events.h"
#include "relay_pulse.h"
#include "output_ctrl.h"
#include "io_scan.h"
#include "sntp_client.h"
#include "ota.h"
#include "netbiosns.h"
#include "buildinfo.h"
#include "webui.h"
#include "pal_sys.h"

//*****************************************************************************
//
//! \addtogroup example_list
//! <h1>Ethernet-based I/O Control (enet_io)</h1>
//!
//! This example application demonstrates web-based I/O control using the
//! Tiva Ethernet controller and the lwIP TCP/IP Stack.  DHCP is used to
//! obtain an Ethernet address.  If DHCP times out without obtaining an
//! address, a static IP address will be chosen using AutoIP.  The address that
//! is selected will be shown on the UART allowing you to access the
//! internal web pages served by the application via your normal web browser.
//!
//! Two different methods of controlling board peripherals via web pages are
//! illustrated via pages labeled ``IO Control Demo 1'' and ``IO Control
//! Demo 2'' in the navigation menu on the left of the application's home page.
//! In both cases, the example allows you to toggle the state of the user LED
//! on the board and set the speed of a blinking LED.
//!
//! ``IO Control Demo 1'' uses JavaScript running in the web browser to send
//! HTTP requests for particular special URLs.  These special URLs are
//! intercepted in the file system support layer (io_fs.c) and used to
//! control the LED and animation LED.  Responses generated by the board are
//! returned to the browser and inserted into the page HTML dynamically by
//! more JavaScript code.
//!
//! ``IO Control Demo 2'' uses standard HTML forms to pass parameters to CGI
//! (Common Gateway Interface) handlers running on the board.  These handlers
//! process the form data and control the animation and LED as requested before
//! sending a response page (in this case, the original form) back to the
//! browser.  The application registers the names and handlers for each of its
//! CGIs with the HTTPD server during initialization and the server calls
//! these handlers after parsing URL parameters each time one of the CGI URLs
//! is requested.
//!
//! Information on the state of the various controls in the second demo is
//! inserted into the served HTML using SSI (Server Side Include) tags which
//! are parsed by the HTTPD server in the application.  As with the CGI
//! handlers, the application registers its list of SSI tags and a handler
//! function with the web server during initialization and this handler is
//! called whenever any registered tag is found in a .shtml, .ssi, .shtm or
//! .xml file being served to the browser.
//!
//! In addition to LED and animation speed control, the second example also
//! allows a line of text to be sent to the board for output to the UART.
//! This is included to illustrate the decoding of HTTP text strings.
//!
//! Note that the web server used by this example has been modified from the
//! example shipped with the basic lwIP package.  Additions include SSI and
//! CGI support along with the ability to have the server automatically insert
//! the HTTP headers rather than having these built in to the files in the
//! file system image.
//!
//! Source files for the internal file system image can be found in the ``fs''
//! directory.  If any of these files are changed, the file system image
//! (io_fsdata.h) should be rebuilt by running the following command from the
//! enet_io directory:
//!
//! ../../../../tools/bin/makefsfile -i fs -o io_fsdata.h -r -h -q
//!
//! For additional details on lwIP, refer to the lwIP web page at:
//! http://savannah.nongnu.org/projects/lwip/
//
//*****************************************************************************

//*****************************************************************************
//
// Defines for setting up the system clock.
//
//*****************************************************************************
#define SYSTICKHZ               100
#define SYSTICKMS               (1000 / SYSTICKHZ)

//*****************************************************************************
//
// Interrupt priority definitions.  The top 3 bits of these values are
// significant with lower values indicating higher priority interrupts.
//
//*****************************************************************************
#define SYSTICK_INT_PRIORITY    0x80
#define ETHERNET_INT_PRIORITY   0xC0

//*****************************************************************************
//
// A set of flags.  The flag bits are defined as follows:
//
//     0 -> An indicator that the animation timer interrupt has occurred.
//
//*****************************************************************************
#define FLAG_TICK            0
static volatile unsigned long g_ulFlags;

//*****************************************************************************
//
// External Application references.
//
//*****************************************************************************
extern void httpd_init(void);

//
// Page returned by the OTA chunk handler on a parameter error.  (The other CGI
// response-page macros moved to common/webui.c together with their handlers.)
//
#define DEFAULT_CGI_RESPONSE    "/index.shtml"

//
// Convert one ASCII hex character to its 4-bit value.  Used by the OTA chunk
// decoder below; the web UI keeps its own copy in common/webui.c.
//
static uint8_t
HexNibble(char c)
{
    if((c >= '0') && (c <= '9')) { return((uint8_t)(c - '0')); }
    if((c >= 'a') && (c <= 'f')) { return((uint8_t)(c - 'a' + 10)); }
    if((c >= 'A') && (c <= 'F')) { return((uint8_t)(c - 'A' + 10)); }
    return(0);
}




//*****************************************************************************
//
// Timeout for DHCP address request (in seconds).
//
//*****************************************************************************
#ifndef DHCP_EXPIRE_TIMER_SECS
#define DHCP_EXPIRE_TIMER_SECS  45
#endif


//*****************************************************************************
//
// MQTT IO integration state: a periodic tick flag set by SysTick, and a
// request flag asking the main loop to (re)start the MQTT connection (set
// when an IP is acquired or the configuration changes via the web UI).
//
//*****************************************************************************
static volatile bool g_bSysTickFlag;


//
// OTA upload state — written from the CGI handler (Ethernet ISR context).
//
static uint32_t g_ui32OTAWriteAddr;
static uint32_t g_ui32OTASize;
static uint8_t  g_ui8OTAAlignBuf[4];
static uint32_t g_ui32OTAAlignLen;
static uint32_t g_ui32OTALastErasedPage;
static bool     g_bOTAAbort;    // set on staging overflow — blocks the commit
static int32_t  g_i32OTANextSeq; // next chunk seq expected (idempotent retries)

//*****************************************************************************
//
// The system clock frequency.  Used by the SD card driver.
//
//*****************************************************************************
uint32_t g_ui32SysClock;

//*****************************************************************************
//
// The error routine that is called if the driver library encounters an error.
//
//*****************************************************************************
#ifdef DEBUG
void
__error__(char *pcFilename, uint32_t ui32Line)
{
}
#endif

//*****************************************************************************
//
// This function is called by the HTTP server whenever it encounters an SSI
// tag in a web page.  The iIndex parameter provides the index of the tag in
// the g_pcConfigSSITags array. This function writes the substitution text
// into the pcInsert array, writing no more than iInsertLen characters.
//
//*****************************************************************************
//*****************************************************************************
//
// FwChunkCGIHandler - Receives one hex-encoded binary chunk of an OTA image.
//
// URL format (GET):
//   /fwchunk.cgi?seq=N&last=0&data=HEXHEX...
//
// seq=0 initialises the upload and erases the header page + first image page.
// Each subsequent request appends to the staging flash.
// last=1 flushes the alignment buffer, computes CRC32, writes the OTA header
// and EEPROM flag, then schedules a system reset.
//
// The hex-encoded payload carries up to ~494 binary bytes per request
// (limited by LWIP_HTTPD_MAX_URI_LEN = 1024).
//
//*****************************************************************************
char *
WebPlatformOtaChunkCGI(int32_t iIndex, int32_t i32NumParams,
                  char *pcParam[], char *pcValue[])
{
    int32_t  iSeqIdx, iLastIdx, iDataIdx;
    int32_t  iSeqNum;
    bool     bLast;
    const char *pcData;
    uint32_t ui32DataHexLen, i;
    uint32_t ui32PageAddr;
    tOTAHeader sHdr;
    uint32_t ui32Crc;

    iSeqIdx  = FindCGIParameter("seq",  pcParam, i32NumParams);
    iLastIdx = FindCGIParameter("last", pcParam, i32NumParams);
    iDataIdx = FindCGIParameter("data", pcParam, i32NumParams);

    if(iSeqIdx < 0 || iDataIdx < 0)
    {
        return(DEFAULT_CGI_RESPONSE);
    }

    iSeqNum = (int32_t)ustrtoul(pcValue[iSeqIdx], NULL, 10);
    bLast   = (iLastIdx >= 0) && (pcValue[iLastIdx][0] == '1');
    pcData  = pcValue[iDataIdx];
    ui32DataHexLen = ustrlen(pcData) & ~1u; // must be even (pairs of hex chars)

    //
    // First chunk: reset state and pre-erase the header and first image page.
    //
    if(iSeqNum == 0)
    {
        g_ui32OTAWriteAddr    = OTA_IMAGE_ADDR;
        g_ui32OTASize         = 0;
        g_ui32OTAAlignLen     = 0;
        g_ui32OTALastErasedPage = OTA_IMAGE_ADDR;
        g_bOTAAbort           = false;
        g_i32OTANextSeq       = 0;

        MAP_FlashErase(OTA_HEADER_ADDR);
        MAP_FlashErase(OTA_IMAGE_ADDR);

        UARTprintf("OTA: upload started.\n");
    }

    //
    // Once a chunk has overflowed the staging region (or otherwise failed),
    // ignore every further chunk until a fresh seq==0 restarts the upload.
    //
    if(g_bOTAAbort)
    {
        return("/tools.shtml");
    }

    //
    // Ordering / idempotency guard, so a dropped connection can be safely retried
    // by the client resending the SAME chunk.  Each seq is applied exactly once,
    // in order:
    //   seq <  next -> already applied (a retry whose response was lost) -> ACK
    //                  without re-writing, keeping the byte stream intact.
    //   seq >  next -> a chunk was missed -> abort; the client restarts at seq 0.
    //   seq == next -> apply it below, then advance g_i32OTANextSeq.
    //
    if(iSeqNum < g_i32OTANextSeq)
    {
        return(bLast ? "/fwupdate_ok.shtml" : "/tools.shtml");
    }
    if(iSeqNum > g_i32OTANextSeq)
    {
        g_bOTAAbort = true;
        UARTprintf("OTA: out-of-order chunk (got %d, want %d), aborting.\n",
                   iSeqNum, g_i32OTANextSeq);
        return("/tools.shtml");
    }

    //
    // Decode hex bytes and write to staging flash in 4-byte aligned words.
    //
    for(i = 0; i < ui32DataHexLen; i += 2)
    {
        g_ui8OTAAlignBuf[g_ui32OTAAlignLen++] =
            (uint8_t)((HexNibble(pcData[i]) << 4) | HexNibble(pcData[i + 1]));
        g_ui32OTASize++;

        if(g_ui32OTAAlignLen == 4)
        {
            //
            // Never write past the end of the staging region.  A too-large image
            // (or a buggy/hostile client) would otherwise erase and program past
            // the OTA image slot into invalid flash.  Abort and block the commit.
            //
            if(g_ui32OTAWriteAddr >= OTA_IMAGE_ADDR + OTA_IMAGE_MAX_SIZE)
            {
                g_bOTAAbort       = true;
                g_ui32OTAAlignLen = 0;
                UARTprintf("OTA: image exceeds %u-byte staging region, aborting.\n",
                           (unsigned)OTA_IMAGE_MAX_SIZE);
                break;
            }

            //
            // Erase the next 16 KB page when the write pointer first enters it.
            //
            ui32PageAddr = g_ui32OTAWriteAddr & ~(0x4000u - 1u);
            if(ui32PageAddr > g_ui32OTALastErasedPage)
            {
                MAP_FlashErase(ui32PageAddr);
                g_ui32OTALastErasedPage = ui32PageAddr;
            }

            MAP_FlashProgram((uint32_t *)(uintptr_t)g_ui8OTAAlignBuf,
                             g_ui32OTAWriteAddr, 4);
            g_ui32OTAWriteAddr += 4;
            g_ui32OTAAlignLen   = 0;
        }
    }

    //
    // Chunk fully applied — advance so a resend of this same seq is treated as a
    // duplicate ACK (idempotent retry) and the next seq is the one expected.
    //
    if(!g_bOTAAbort)
    {
        g_i32OTANextSeq++;
    }

    //
    // Last chunk: flush any partial word (pad with 0xFF), then finalise.
    //
    if(bLast)
    {
        int32_t  iTotLenIdx, iTotCrcIdx;
        uint32_t ui32TotLen, ui32TotCrc;

        //
        // If any chunk overflowed the staging region, never commit: no header is
        // written and no pending flag is set, so the next boot keeps the current
        // firmware.
        //
        if(g_bOTAAbort)
        {
            UARTprintf("OTA: upload aborted, not committing.\n");
            return("/tools.shtml");
        }

        if(g_ui32OTAAlignLen > 0)
        {
            while(g_ui32OTAAlignLen < 4)
            {
                g_ui8OTAAlignBuf[g_ui32OTAAlignLen++] = 0xFF;
            }
            MAP_FlashProgram((uint32_t *)(uintptr_t)g_ui8OTAAlignBuf,
                             g_ui32OTAWriteAddr, 4);
            g_ui32OTAWriteAddr += 4;
            g_ui32OTAAlignLen   = 0;
        }

        //
        // End-to-end integrity check.  The client sends the total byte count and
        // CRC32 of the ORIGINAL file (totlen/totcrc).  A truncated, reordered or
        // corrupted upload will not match, so it is rejected BEFORE the image is
        // committed.  Without this the header CRC is only computed over whatever
        // bytes happened to arrive, so a short upload looks self-consistent.
        //
        iTotLenIdx = FindCGIParameter("totlen", pcParam, i32NumParams);
        iTotCrcIdx = FindCGIParameter("totcrc", pcParam, i32NumParams);
        if(iTotLenIdx < 0 || iTotCrcIdx < 0)
        {
            UARTprintf("OTA: missing totlen/totcrc, rejecting.\n");
            return("/tools.shtml");
        }
        ui32TotLen = (uint32_t)ustrtoul(pcValue[iTotLenIdx], NULL, 10);
        ui32TotCrc = (uint32_t)ustrtoul(pcValue[iTotCrcIdx], NULL, 16);

        //
        // CRC32 the staged image (over exactly the received byte count).
        //
        ui32Crc = ConfigCRC32((const uint8_t *)OTA_IMAGE_ADDR, g_ui32OTASize);

        if((g_ui32OTASize != ui32TotLen) || (ui32Crc != ui32TotCrc))
        {
            UARTprintf("OTA: integrity check failed "
                       "(len %u/%u, crc 0x%08x/0x%08x), rejecting.\n",
                       g_ui32OTASize, ui32TotLen, ui32Crc, ui32TotCrc);
            return("/tools.shtml");
        }

        //
        // Verified.  Write the header to 0x80000 and arm the pending flag.
        //
        sHdr.ui32Magic = OTA_HDR_MAGIC;
        sHdr.ui32Size  = g_ui32OTASize;
        sHdr.ui32CRC32 = ui32Crc;
        sHdr.ui32Rsvd  = 0;
        MAP_FlashProgram((uint32_t *)(uintptr_t)&sHdr,
                         OTA_HEADER_ADDR, sizeof(tOTAHeader));

        //
        // Set EEPROM pending flag so the next boot applies the update.
        //
        OtaSetPending(g_ui32OTASize);

        UARTprintf("OTA: %u bytes, CRC=0x%08x verified. Rebooting...\n",
                   g_ui32OTASize, ui32Crc);

        //
        // Signal the main loop to reset after the HTTP response is sent.
        //
        WebUIRequestReset();
        return("/fwupdate_ok.shtml");
    }

    return("/tools.shtml");
}

//*****************************************************************************
//
// WebPlatformOtaMaxBytes - largest OTA image this platform stages, rendered by
// the shared "otamax" SSI tag.  On the TM4C that is the internal-flash staging
// region (OTA_IMAGE_MAX_SIZE); the browser rejects anything larger up front.
//
//*****************************************************************************
uint32_t
WebPlatformOtaMaxBytes(void)
{
    return(OTA_IMAGE_MAX_SIZE);
}

//*****************************************************************************
//
// CheckHWFactoryReset - Check SW1 (PJ0) at startup.
//
// If SW1 is held continuously for 5 seconds, all EEPROM records are
// invalidated and the device resets.  LED D1 (PN1) blinks as a countdown
// indicator.  Releasing SW1 at any point cancels the operation.
//
// Call after ConfigInit() (EEPROM must be initialised) but before the
// network stack starts.
//
//*****************************************************************************
static void
CheckHWFactoryReset(void)
{
    uint32_t ui32Count;

    //
    // Enable the GPIO ports used by SW1 (Port J) and LED D1 (Port N).
    // PinoutSet() may already have done this, but enabling twice is harmless.
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOJ);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPION);
    while(!MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_GPIOJ) ||
          !MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_GPION))
    {
    }

    //
    // PJ0 input with weak pull-up (SW1 is active-low).
    //
    MAP_GPIODirModeSet(GPIO_PORTJ_BASE, GPIO_PIN_0, GPIO_DIR_MODE_IN);
    MAP_GPIOPadConfigSet(GPIO_PORTJ_BASE, GPIO_PIN_0,
                         GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);

    //
    // PN1 output for LED D1 (active-high, off initially).
    //
    MAP_GPIODirModeSet(GPIO_PORTN_BASE, GPIO_PIN_1, GPIO_DIR_MODE_OUT);
    MAP_GPIOPadConfigSet(GPIO_PORTN_BASE, GPIO_PIN_1,
                         GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, 0);

    //
    // Quick exit if SW1 is not held at boot.
    //
    if(MAP_GPIOPinRead(GPIO_PORTJ_BASE, GPIO_PIN_0) != 0)
    {
        return;
    }

    UARTprintf("HW factory reset: keep SW1 held for 5s to confirm...\n");

    //
    // 500 x 10ms = 5 000ms countdown.  LED blinks every 500ms.
    //
    for(ui32Count = 0; ui32Count < 500; ui32Count++)
    {
        //
        // Toggle LED every 50 iterations (~500ms period).
        //
        MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1,
                         ((ui32Count / 50) & 1) ? GPIO_PIN_1 : 0);

        MAP_SysCtlDelay(g_ui32SysClock / 300);   // ~10 ms at 120 MHz

        if(MAP_GPIOPinRead(GPIO_PORTJ_BASE, GPIO_PIN_0) != 0)
        {
            MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, 0);
            UARTprintf("HW factory reset: cancelled (SW1 released).\n");
            return;
        }
    }

    //
    // SW1 held for 5 seconds — perform factory reset.
    //
    MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, GPIO_PIN_1); // LED on solid
    UARTprintf("HW factory reset: erasing EEPROM...\n");
    MQTTAppStop();
    ConfigFactoryReset();
    UARTprintf("HW factory reset: rebooting...\n");
    MAP_SysCtlDelay(g_ui32SysClock / 3);
    MAP_SysCtlReset();
}


//*****************************************************************************
//
// The interrupt handler for the SysTick interrupt.
//
//*****************************************************************************
void
SysTickIntHandler(void)
{
    //
    // Call the lwIP timer handler.
    //
    lwIPTimer(SYSTICKMS);

    //
    // Flag a periodic application tick for the main loop (MQTT keep-alive /
    // reconnect service).
    //
    g_bSysTickFlag = true;
}

//*****************************************************************************
//
// The interrupt handler for the timer used to pace the animation.
//
//*****************************************************************************
void
AnimTimerIntHandler(void)
{
    //
    // Clear the timer interrupt.
    //
    MAP_TimerIntClear(TIMER2_BASE, TIMER_TIMA_TIMEOUT);

    //
    // Indicate that a timer interrupt has occurred.
    //
    HWREGBITW(&g_ulFlags, FLAG_TICK) = 1;
}

//*****************************************************************************
//
// Display an lwIP type IP Address.
//
//*****************************************************************************
void
DisplayIPAddress(uint32_t ui32Addr)
{
    char pcBuf[16];

    //
    // Convert the IP Address into a string.
    //
    usprintf(pcBuf, "%d.%d.%d.%d", ui32Addr & 0xff, (ui32Addr >> 8) & 0xff,
            (ui32Addr >> 16) & 0xff, (ui32Addr >> 24) & 0xff);

    //
    // Display the string.
    //
    UARTprintf(pcBuf);
}

//*****************************************************************************
//
// Required by lwIP library to support any host-related timer functions.
//
//*****************************************************************************
void
lwIPHostTimerHandler(void)
{
    uint32_t ui32NewIPAddress;

    //
    // Get the current IP address.
    //
    ui32NewIPAddress = lwIPLocalIPAddrGet();

    //
    // See if the IP address has changed.
    //
    if(ui32NewIPAddress != g_ui32IPAddress)
    {
        //
        // See if there is an IP address assigned.
        //
        if(ui32NewIPAddress == 0xffffffff)
        {
            //
            // Indicate that there is no link.
            //
            UARTprintf("Waiting for link.\n");
        }
        else if(ui32NewIPAddress == 0)
        {
            //
            // There is no IP address, so indicate that the DHCP process is
            // running.
            //
            UARTprintf("Waiting for IP address.\n");
        }
        else
        {
            //
            // Display the new IP address.
            //
            UARTprintf("IP Address: ");
            DisplayIPAddress(ui32NewIPAddress);
            UARTprintf("\n");
            UARTprintf("Open a browser and enter the IP address.\n");

            //
            // We now have network connectivity: ask the main loop to bring up
            // the MQTT connection (if a broker has been configured).
            //
            WebUIRequestMqttApply();
            SntpInit();
        }

        //
        // Save the new IP address.
        //
        g_ui32IPAddress = ui32NewIPAddress;
    }

    //
    // If there is not an IP address.
    //
    if((ui32NewIPAddress == 0) || (ui32NewIPAddress == 0xffffffff))
    {
        //
        // Do nothing and keep waiting.
        //
    }
}

//*****************************************************************************
//
// This application uses the Ethernet controller and lwIP TCP/IP stack to
// implement a web-configurable MQTT node.  Broker parameters are set via an
// on-board web page; the control board's field I/O is exposed over MQTT.
//
//*****************************************************************************
int
main(void)

{
    uint32_t ui32User0, ui32User1;
    uint8_t pui8MACArray[8];

    //
    // Make sure the main oscillator is enabled because this is required by
    // the PHY.  The system must have a 25MHz crystal attached to the OSC
    // pins.  The SYSCTL_MOSC_HIGHFREQ parameter is used when the crystal
    // frequency is 10MHz or higher.
    //
    SysCtlMOSCConfigSet(SYSCTL_MOSC_HIGHFREQ);

    //
    // Run from the PLL at 120 MHz.
    // Note: SYSCTL_CFG_VCO_240 is a new setting provided in TivaWare 2.2.x and
    // later to better reflect the actual VCO speed due to SYSCTL#22.
    //
    g_ui32SysClock = MAP_SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ |
                                             SYSCTL_OSC_MAIN |
                                             SYSCTL_USE_PLL |
                                             SYSCTL_CFG_VCO_240), 120000000);

    //
    // Configure the device pins.
    //
    PinoutSet(true, false);

    //
    // Configure debug port for internal use.
    //
    UARTStdioConfig(0, 115200, g_ui32SysClock);

    //
    // Clear the terminal and print a banner.
    //
    UARTprintf("\033[2J\033[H");
    UARTprintf("TM4C1294 MQTT IO\n\n");

    //
    // Load persistent MQTT configuration from EEPROM.
    //
    ConfigInit();

    //
    // If a firmware update was staged before the last reset, validate it and
    // apply it now (OtaCheckAndApply calls OtaApply which never returns).
    //
    OtaCheckAndApply();

    //
    // Check if SW1 (PJ0) is held at boot for a hardware factory reset.
    // If held for 5 s, EEPROM is erased and the device resets.
    //
    CheckHWFactoryReset();

    //
    // Configure SysTick for a periodic interrupt.
    //
    MAP_SysTickPeriodSet(g_ui32SysClock / SYSTICKHZ);
    MAP_SysTickEnable();
    MAP_SysTickIntEnable();

    //
    // Configure the hardware MAC address for Ethernet Controller filtering of
    // incoming packets.  The MAC address will be stored in the non-volatile
    // USER0 and USER1 registers.
    //
    MAP_FlashUserGet(&ui32User0, &ui32User1);
    if((ui32User0 == 0xffffffff) || (ui32User1 == 0xffffffff))
    {
        //
        // Let the user know there is no MAC address
        //
        UARTprintf("No MAC programmed!\n");

        while(1)
        {
        }
    }

    //
    // Tell the user what we are doing just now.
    //
    UARTprintf("Waiting for IP.\n");

    //
    // Convert the 24/24 split MAC address from NV ram into a 32/16 split
    // MAC address needed to program the hardware registers, then program
    // the MAC address into the Ethernet Controller registers.
    //
    pui8MACArray[0] = ((ui32User0 >>  0) & 0xff);
    pui8MACArray[1] = ((ui32User0 >>  8) & 0xff);
    pui8MACArray[2] = ((ui32User0 >> 16) & 0xff);
    pui8MACArray[3] = ((ui32User1 >>  0) & 0xff);
    pui8MACArray[4] = ((ui32User1 >>  8) & 0xff);
    pui8MACArray[5] = ((ui32User1 >> 16) & 0xff);

    //
    // Initialize the lwIP library, using DHCP.
    //
    lwIPInit(g_ui32SysClock, pui8MACArray, 0, 0, 0, IPADDR_USE_DHCP);

    //
    // Set the DHCP hostname to the client ID directly (sanitized to the
    // DNS-legal set: letters, digits, hyphen).  A router that registers DHCP
    // hostnames can then resolve e.g. "http://m35/".  The NetBIOS responder
    // (NetbiosnsInit below) makes the same name resolvable on Windows even when
    // the router does not.  The static buffer persists for the lifetime of the
    // program; netif_list points to the single netif added by lwIPInit().
    //
    {
        static char pcHostname[CFG_CLIENTID_LEN];
        const char *pcId = ConfigGet()->pcClientID;
        uint32_t ui32i;
        for(ui32i = 0; (pcId[ui32i] != '\0') &&
                       (ui32i < (sizeof(pcHostname) - 1)); ui32i++)
        {
            char c = pcId[ui32i];
            if(((c >= 'a') && (c <= 'z')) || ((c >= 'A') && (c <= 'Z')) ||
               ((c >= '0') && (c <= '9')))
            {
                pcHostname[ui32i] = c;
            }
            else
            {
                pcHostname[ui32i] = '-';
            }
        }
        pcHostname[ui32i] = '\0';
        netif_set_hostname(netif_list, pcHostname);
    }

    //
    // Setup the device locator service.
    //
    LocatorInit();
    LocatorMACAddrSet(pui8MACArray);
    LocatorAppTitleSet("EK-TM4C1294XL MQTT IO");

    //
    // Initialize a sample httpd server.
    //
    httpd_init();

    //
    // Start the NetBIOS name responder so the board is reachable by its client
    // ID (e.g. "http://m35/") from a Windows host without knowing its IP.
    //
    NetbiosnsInit();

    //
    // Set the interrupt priorities.  We set the SysTick interrupt to a higher
    // priority than the Ethernet interrupt to ensure that the file system
    // tick is processed if SysTick occurs while the Ethernet handler is being
    // processed.  This is very likely since all the TCP/IP and HTTP work is
    // done in the context of the Ethernet interrupt.
    //
    MAP_IntPrioritySet(INT_EMAC0, ETHERNET_INT_PRIORITY);
    MAP_IntPrioritySet(FAULT_SYSTICK, SYSTICK_INT_PRIORITY);

    //
    // Register the config web UI's SSI + CGI handlers (shared with the CC35x1
    // build; the tag/URI tables and handler bodies now live in common/webui.c).
    //
    WebUIRegister();

    //
    // Initialize IO controls (legacy web-demo LED / animation timer).
    //
    io_init();

    //
    // Initialize the field-I/O chains with the configured device counts.  The
    // relay chain powers up with all relays off and outputs enabled.
    //
    DINChainInit(ConfigGetDinDevices());
    RelayChainInit(ConfigGetRelayDevices());
    OutputCtrlReload();   // load per-output modes + shutter table
    UARTprintf("IO: %d input dev, %d relay dev.\n", ConfigGetDinDevices(),
               ConfigGetRelayDevices());

    //
    // Initialize the MQTT client subsystem (MAC seeds the HA device id).
    //
    MQTTAppInit(pui8MACArray);

    //
    // Wire the input-scan / binding engine to the click detector.
    //
    IOScanInit();

    //
    // Main loop.  Networking (lwIP, httpd, MQTT receive) runs in interrupt
    // context; here we service the periodic application tick: apply pending
    // (re)connect requests and drive the MQTT keep-alive/reconnect timers.
    //
    while(1)
    {
        //
        // If the OTA last-chunk handler requested a reset, wait one tick so
        // the HTTP response is delivered, then reset into the new firmware.
        //
        if(WebUIResetPending())
        {
            MAP_SysCtlDelay(g_ui32SysClock / 3);  // ~333 ms — let TCP flush
            PalReboot();
        }

        //
        // Wait for the next SysTick (~10 ms) application tick.
        //
        while(!g_bSysTickFlag)
        {
        }
        g_bSysTickFlag = false;

        //
        // Apply a pending (re)connect request from DHCP completion or a web
        // configuration change.
        //
        if(WebUIMqttApplyPending())
        {
            //
            // A config change may also have altered the device counts.  Only
            // reconfigure the relay chain when its count actually changed, so an
            // unrelated setting change does not switch the relays off.
            //
            DINChainSetDevices(ConfigGetDinDevices());
            if(RelayChainGetDevices() != ConfigGetRelayDevices())
            {
                RelayChainSetDevices(ConfigGetRelayDevices());
            }
            OutputCtrlReload();   // pick up any output-mode / shutter changes
            MQTTAppStart();
        }

        //
        // Re-publish HA discovery after an I/O configuration change (without
        // a full reconnect — the broker session stays live).
        //
        if(WebUIMqttRepublishPending())
        {
            MQTTAppRepublish();
        }

        //
        // Poll the input chain and the relay fault line; publish changes, run
        // bindings, log any transitions.
        //
        IOScanTick();

        //
        // Advance pushbutton click-detection timers.
        //
        InputEventsTick(SYSTICKMS);
        RelayPulseTick(SYSTICKMS);
        OutputCtrlTick(SYSTICKMS);
        SntpTick(SYSTICKMS);

        //
        // Service MQTT keep-alive, reconnect timers and the post-connect
        // publish sequence.
        //
        MQTTAppTick(SYSTICKMS);
    }
}
