//*****************************************************************************
//
// enet_io.c - I/O control via a web server.
//
// Copyright (c) 2013-2020 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
// Texas Instruments (TI) is supplying this software for use solely and
// exclusively on TI's microcontroller products. The software is owned by
// TI and/or its suppliers, and is protected under applicable copyright
// laws. You may not combine this software with "viral" open-source
// software in order to form a larger program.
// 
// THIS SOFTWARE IS PROVIDED "AS IS" AND WITH ALL FAULTS.
// NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
// NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. TI SHALL NOT, UNDER ANY
// CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, FOR ANY REASON WHATSOEVER.
// 
// This is part of revision 2.2.0.295 of the EK-TM4C1294XL Firmware Package.
//
//*****************************************************************************

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_types.h"
#include "driverlib/flash.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "driverlib/timer.h"
#include "utils/locator.h"
#include "utils/lwiplib.h"
#include "utils/uartstdio.h"
#include "utils/ustdlib.h"
#include "httpserver_raw/httpd.h"
#include "drivers/pinout.h"
#include "io.h"
#include "cgifuncs.h"
#include "config.h"
#include "mqtt_app.h"
#include "din_chain.h"
#include "relay_chain.h"

//*****************************************************************************
//
//! \addtogroup example_list
//! <h1>Ethernet-based I/O Control (enet_io)</h1>
//!
//! This example application demonstrates web-based I/O control using the
//! Tiva Ethernet controller and the lwIP TCP/IP Stack.  DHCP is used to
//! obtain an Ethernet address.  If DHCP times out without obtaining an
//! address, a static IP address will be chosen using AutoIP.  The address that
//! is selected will be shown on the UART allowing you to access the
//! internal web pages served by the application via your normal web browser.
//!
//! Two different methods of controlling board peripherals via web pages are
//! illustrated via pages labeled ``IO Control Demo 1'' and ``IO Control
//! Demo 2'' in the navigation menu on the left of the application's home page.
//! In both cases, the example allows you to toggle the state of the user LED
//! on the board and set the speed of a blinking LED.
//!
//! ``IO Control Demo 1'' uses JavaScript running in the web browser to send
//! HTTP requests for particular special URLs.  These special URLs are
//! intercepted in the file system support layer (io_fs.c) and used to
//! control the LED and animation LED.  Responses generated by the board are
//! returned to the browser and inserted into the page HTML dynamically by
//! more JavaScript code.
//!
//! ``IO Control Demo 2'' uses standard HTML forms to pass parameters to CGI
//! (Common Gateway Interface) handlers running on the board.  These handlers
//! process the form data and control the animation and LED as requested before
//! sending a response page (in this case, the original form) back to the
//! browser.  The application registers the names and handlers for each of its
//! CGIs with the HTTPD server during initialization and the server calls
//! these handlers after parsing URL parameters each time one of the CGI URLs
//! is requested.
//!
//! Information on the state of the various controls in the second demo is
//! inserted into the served HTML using SSI (Server Side Include) tags which
//! are parsed by the HTTPD server in the application.  As with the CGI
//! handlers, the application registers its list of SSI tags and a handler
//! function with the web server during initialization and this handler is
//! called whenever any registered tag is found in a .shtml, .ssi, .shtm or
//! .xml file being served to the browser.
//!
//! In addition to LED and animation speed control, the second example also
//! allows a line of text to be sent to the board for output to the UART.
//! This is included to illustrate the decoding of HTTP text strings.
//!
//! Note that the web server used by this example has been modified from the
//! example shipped with the basic lwIP package.  Additions include SSI and
//! CGI support along with the ability to have the server automatically insert
//! the HTTP headers rather than having these built in to the files in the
//! file system image.
//!
//! Source files for the internal file system image can be found in the ``fs''
//! directory.  If any of these files are changed, the file system image
//! (io_fsdata.h) should be rebuilt by running the following command from the
//! enet_io directory:
//!
//! ../../../../tools/bin/makefsfile -i fs -o io_fsdata.h -r -h -q
//!
//! For additional details on lwIP, refer to the lwIP web page at:
//! http://savannah.nongnu.org/projects/lwip/
//
//*****************************************************************************

//*****************************************************************************
//
// Defines for setting up the system clock.
//
//*****************************************************************************
#define SYSTICKHZ               100
#define SYSTICKMS               (1000 / SYSTICKHZ)

//*****************************************************************************
//
// Interrupt priority definitions.  The top 3 bits of these values are
// significant with lower values indicating higher priority interrupts.
//
//*****************************************************************************
#define SYSTICK_INT_PRIORITY    0x80
#define ETHERNET_INT_PRIORITY   0xC0

//*****************************************************************************
//
// A set of flags.  The flag bits are defined as follows:
//
//     0 -> An indicator that the animation timer interrupt has occurred.
//
//*****************************************************************************
#define FLAG_TICK            0
static volatile unsigned long g_ulFlags;

//*****************************************************************************
//
// External Application references.
//
//*****************************************************************************
extern void httpd_init(void);

//*****************************************************************************
//
// SSI tag indices for each entry in the g_pcSSITags array.
//
//*****************************************************************************
#define SSI_INDEX_HOST      0
#define SSI_INDEX_PORT      1
#define SSI_INDEX_CLIENT    2
#define SSI_INDEX_USER      3
#define SSI_INDEX_TOPIC     4
#define SSI_INDEX_AUTH      5
#define SSI_INDEX_STATUS    6
#define SSI_INDEX_IP        7
#define SSI_INDEX_DIN       8
#define SSI_INDEX_RELAY     9

//*****************************************************************************
//
// This array holds all the strings that are to be recognized as SSI tag
// names by the HTTPD server.  The server will call SSIHandler to request a
// replacement string whenever the pattern <!--#tagname--> (where tagname
// appears in the following array) is found in ".ssi", ".shtml" or ".shtm"
// files that it serves.
//
//*****************************************************************************
static const char *g_pcConfigSSITags[] =
{
    "mqhost",        // SSI_INDEX_HOST
    "mqport",        // SSI_INDEX_PORT
    "mqclient",      // SSI_INDEX_CLIENT
    "mquser",        // SSI_INDEX_USER
    "mqtopic",       // SSI_INDEX_TOPIC
    "mqauth",        // SSI_INDEX_AUTH
    "mqstatus",      // SSI_INDEX_STATUS
    "ipaddr",        // SSI_INDEX_IP
    "mqdin",         // SSI_INDEX_DIN
    "mqrelay"        // SSI_INDEX_RELAY
};

//*****************************************************************************
//
// The number of individual SSI tags that the HTTPD server can expect to
// find in our configuration pages.
//
//*****************************************************************************
#define NUM_CONFIG_SSI_TAGS     (sizeof(g_pcConfigSSITags) / sizeof (char *))

//*****************************************************************************
//
// Prototypes for the various CGI handler functions.
//
//*****************************************************************************
static char *MQTTConfigCGIHandler(int32_t iIndex, int32_t i32NumParams,
                                  char *pcParam[], char *pcValue[]);

//*****************************************************************************
//
// Prototype for the main handler used to process server-side-includes for the
// application's web-based configuration screens.
//
//*****************************************************************************
static int32_t SSIHandler(int32_t iIndex, char *pcInsert, int32_t iInsertLen);

//*****************************************************************************
//
// CGI URI indices for each entry in the g_psConfigCGIURIs array.
//
//*****************************************************************************
#define CGI_INDEX_MQTTCFG       0

//*****************************************************************************
//
// This array is passed to the HTTPD server to inform it of special URIs
// that are treated as common gateway interface (CGI) scripts.  Each URI name
// is defined along with a pointer to the function which is to be called to
// process it.
//
//*****************************************************************************
static const tCGI g_psConfigCGIURIs[] =
{
    { "/mqttcfg.cgi", (tCGIHandler)MQTTConfigCGIHandler } // CGI_INDEX_MQTTCFG
};

//*****************************************************************************
//
// The number of individual CGI URIs that are configured for this system.
//
//*****************************************************************************
#define NUM_CONFIG_CGI_URIS     (sizeof(g_psConfigCGIURIs) / sizeof(tCGI))

//*****************************************************************************
//
// The file sent back to the browser by default following completion of any
// of our CGI handlers.  Each individual handler returns the URI of the page
// to load in response to it being called.
//
//*****************************************************************************
#define DEFAULT_CGI_RESPONSE    "/index.shtml"

//*****************************************************************************
//
// The file sent back to the browser in cases where a parameter error is
// detected by one of the CGI handlers.  This should only happen if someone
// tries to access the CGI directly via the broswer command line and doesn't
// enter all the required parameters alongside the URI.
//
//*****************************************************************************
#define PARAM_ERROR_RESPONSE    "/perror.htm"

#define JAVASCRIPT_HEADER                                                     \
    "<script type='text/javascript' language='JavaScript'><!--\n"
#define JAVASCRIPT_FOOTER                                                     \
    "//--></script>\n"

//*****************************************************************************
//
// Timeout for DHCP address request (in seconds).
//
//*****************************************************************************
#ifndef DHCP_EXPIRE_TIMER_SECS
#define DHCP_EXPIRE_TIMER_SECS  45
#endif

//*****************************************************************************
//
// The current IP address.
//
//*****************************************************************************
uint32_t g_ui32IPAddress;

//*****************************************************************************
//
// MQTT IO integration state: a periodic tick flag set by SysTick, and a
// request flag asking the main loop to (re)start the MQTT connection (set
// when an IP is acquired or the configuration changes via the web UI).
//
//*****************************************************************************
static volatile bool g_bSysTickFlag;
static volatile bool g_bStartMQTT;

//*****************************************************************************
//
// The system clock frequency.  Used by the SD card driver.
//
//*****************************************************************************
uint32_t g_ui32SysClock;

//*****************************************************************************
//
// The error routine that is called if the driver library encounters an error.
//
//*****************************************************************************
#ifdef DEBUG
void
__error__(char *pcFilename, uint32_t ui32Line)
{
}
#endif

//*****************************************************************************
//
// Helper: copy a (possibly URL-encoded) CGI parameter into a fixed buffer.
//
//*****************************************************************************
static void
GetStringParam(const char *pcName, char *pcParam[], char *pcValue[],
               int32_t i32NumParams, char *pcDest, int32_t i32DestLen)
{
    int32_t i32Idx = FindCGIParameter(pcName, pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        DecodeFormString(pcValue[i32Idx], pcDest, i32DestLen);
    }
}

//*****************************************************************************
//
// CGI handler for /mqttcfg.cgi.  Parses the configuration form, stores the
// new settings in EEPROM and requests a reconnect.
//
//*****************************************************************************
static char *
MQTTConfigCGIHandler(int32_t iIndex, int32_t i32NumParams, char *pcParam[],
                     char *pcValue[])
{
    tMQTTConfig *psCfg = ConfigGet();
    int32_t i32Idx;

    (void)iIndex;

    //
    // String fields.  Empty values are accepted (e.g. to clear the host).
    //
    psCfg->pcHost[0] = '\0';
    GetStringParam("host", pcParam, pcValue, i32NumParams, psCfg->pcHost,
                   CFG_HOST_LEN);
    GetStringParam("client", pcParam, pcValue, i32NumParams, psCfg->pcClientID,
                   CFG_CLIENTID_LEN);
    GetStringParam("user", pcParam, pcValue, i32NumParams, psCfg->pcUser,
                   CFG_USER_LEN);
    GetStringParam("topic", pcParam, pcValue, i32NumParams, psCfg->pcTopicBase,
                   CFG_TOPIC_LEN);

    //
    // Password: only overwrite the stored value when a non-empty value is
    // submitted (the form never echoes the current password back).
    //
    i32Idx = FindCGIParameter("pass", pcParam, i32NumParams);
    if((i32Idx != -1) && (pcValue[i32Idx][0] != '\0'))
    {
        DecodeFormString(pcValue[i32Idx], psCfg->pcPass, CFG_PASS_LEN);
    }

    //
    // Port number.
    //
    i32Idx = FindCGIParameter("port", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        uint32_t ui32Port = ustrtoul(pcValue[i32Idx], 0, 10);
        psCfg->ui16Port = (ui32Port && (ui32Port <= 65535)) ?
                          (uint16_t)ui32Port : 1883;
    }

    //
    // Cascaded device counts (8 channels each).  The setters clamp out-of-range
    // values to the compiled-in default.
    //
    i32Idx = FindCGIParameter("din", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        ConfigSetDinDevices((uint8_t)ustrtoul(pcValue[i32Idx], 0, 10));
    }
    i32Idx = FindCGIParameter("relay", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        ConfigSetRelayDevices((uint8_t)ustrtoul(pcValue[i32Idx], 0, 10));
    }

    //
    // Authentication checkbox (present in the form only when ticked).
    //
    psCfg->ui8UseAuth =
        (FindCGIParameter("auth", pcParam, i32NumParams) != -1) ? 1 : 0;

    //
    // Persist and ask the main loop to apply the new settings.
    //
    ConfigSave();
    g_bStartMQTT = true;

    return(DEFAULT_CGI_RESPONSE);
}

//*****************************************************************************
//
// This function is called by the HTTP server whenever it encounters an SSI
// tag in a web page.  The iIndex parameter provides the index of the tag in
// the g_pcConfigSSITags array. This function writes the substitution text
// into the pcInsert array, writing no more than iInsertLen characters.
//
//*****************************************************************************
static int32_t
SSIHandler(int32_t iIndex, char *pcInsert, int32_t iInsertLen)
{
    tMQTTConfig *psCfg = ConfigGet();

    //
    // Which SSI tag have we been passed?  (The password is intentionally never
    // echoed back to the browser.)
    //
    switch(iIndex)
    {
        case SSI_INDEX_HOST:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcHost);
            break;

        case SSI_INDEX_PORT:
            usnprintf(pcInsert, iInsertLen, "%d", psCfg->ui16Port);
            break;

        case SSI_INDEX_CLIENT:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcClientID);
            break;

        case SSI_INDEX_USER:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcUser);
            break;

        case SSI_INDEX_TOPIC:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcTopicBase);
            break;

        case SSI_INDEX_DIN:
            usnprintf(pcInsert, iInsertLen, "%d", ConfigGetDinDevices());
            break;

        case SSI_INDEX_RELAY:
            usnprintf(pcInsert, iInsertLen, "%d", ConfigGetRelayDevices());
            break;

        case SSI_INDEX_AUTH:
            usnprintf(pcInsert, iInsertLen, "%s",
                      psCfg->ui8UseAuth ? "checked" : "");
            break;

        case SSI_INDEX_STATUS:
            usnprintf(pcInsert, iInsertLen, "%s", MQTTAppStatusStr());
            break;

        case SSI_INDEX_IP:
            usnprintf(pcInsert, iInsertLen, "%d.%d.%d.%d",
                      g_ui32IPAddress & 0xff, (g_ui32IPAddress >> 8) & 0xff,
                      (g_ui32IPAddress >> 16) & 0xff,
                      (g_ui32IPAddress >> 24) & 0xff);
            break;

        default:
            usnprintf(pcInsert, iInsertLen, "??");
            break;
    }

    //
    // Tell the server how many characters our insert string contains.
    //
    return(strlen(pcInsert));
}

//*****************************************************************************
//
// The interrupt handler for the SysTick interrupt.
//
//*****************************************************************************
void
SysTickIntHandler(void)
{
    //
    // Call the lwIP timer handler.
    //
    lwIPTimer(SYSTICKMS);

    //
    // Flag a periodic application tick for the main loop (MQTT keep-alive /
    // reconnect service).
    //
    g_bSysTickFlag = true;
}

//*****************************************************************************
//
// The interrupt handler for the timer used to pace the animation.
//
//*****************************************************************************
void
AnimTimerIntHandler(void)
{
    //
    // Clear the timer interrupt.
    //
    MAP_TimerIntClear(TIMER2_BASE, TIMER_TIMA_TIMEOUT);

    //
    // Indicate that a timer interrupt has occurred.
    //
    HWREGBITW(&g_ulFlags, FLAG_TICK) = 1;
}

//*****************************************************************************
//
// Display an lwIP type IP Address.
//
//*****************************************************************************
void
DisplayIPAddress(uint32_t ui32Addr)
{
    char pcBuf[16];

    //
    // Convert the IP Address into a string.
    //
    usprintf(pcBuf, "%d.%d.%d.%d", ui32Addr & 0xff, (ui32Addr >> 8) & 0xff,
            (ui32Addr >> 16) & 0xff, (ui32Addr >> 24) & 0xff);

    //
    // Display the string.
    //
    UARTprintf(pcBuf);
}

//*****************************************************************************
//
// Required by lwIP library to support any host-related timer functions.
//
//*****************************************************************************
void
lwIPHostTimerHandler(void)
{
    uint32_t ui32NewIPAddress;

    //
    // Get the current IP address.
    //
    ui32NewIPAddress = lwIPLocalIPAddrGet();

    //
    // See if the IP address has changed.
    //
    if(ui32NewIPAddress != g_ui32IPAddress)
    {
        //
        // See if there is an IP address assigned.
        //
        if(ui32NewIPAddress == 0xffffffff)
        {
            //
            // Indicate that there is no link.
            //
            UARTprintf("Waiting for link.\n");
        }
        else if(ui32NewIPAddress == 0)
        {
            //
            // There is no IP address, so indicate that the DHCP process is
            // running.
            //
            UARTprintf("Waiting for IP address.\n");
        }
        else
        {
            //
            // Display the new IP address.
            //
            UARTprintf("IP Address: ");
            DisplayIPAddress(ui32NewIPAddress);
            UARTprintf("\n");
            UARTprintf("Open a browser and enter the IP address.\n");

            //
            // We now have network connectivity: ask the main loop to bring up
            // the MQTT connection (if a broker has been configured).
            //
            g_bStartMQTT = true;
        }

        //
        // Save the new IP address.
        //
        g_ui32IPAddress = ui32NewIPAddress;
    }

    //
    // If there is not an IP address.
    //
    if((ui32NewIPAddress == 0) || (ui32NewIPAddress == 0xffffffff))
    {
        //
        // Do nothing and keep waiting.
        //
    }
}

//*****************************************************************************
//
// Poll the SN65HVS882 input chain and log any change over UART.  Called from
// the periodic application tick.  This is bring-up instrumentation - MQTT
// publishing of the inputs will hook in here next.
//
//*****************************************************************************
static void
DINChainScan(void)
{
    static uint8_t pui8Prev[DIN_MAX_BYTES];
    static bool bPrimed;
    uint8_t pui8Cur[DIN_MAX_BYTES];
    uint8_t ui8Bytes, i;

    ui8Bytes = DINChainRead(pui8Cur, sizeof(pui8Cur));
    if(ui8Bytes == 0)
    {
        return;
    }

    //
    // Publish each channel that changed since the previous scan.  Channel c of
    // device d maps to bit (7 - c) of byte d and to input index d*8 + c.  The
    // first scan only primes the baseline; the initial retained state of every
    // input is published by the MQTT post-connect sequence.
    //
    for(i = 0; i < ui8Bytes; i++)
    {
        uint8_t ui8Diff = (uint8_t)(pui8Cur[i] ^ pui8Prev[i]);

        if(bPrimed && ui8Diff)
        {
            int iBit;
            for(iBit = 0; iBit < 8; iBit++)
            {
                uint8_t ui8Mask = (uint8_t)(0x80 >> iBit);
                if(ui8Diff & ui8Mask)
                {
                    int iInput = (i * 8) + iBit;
                    bool bOn = (pui8Cur[i] & ui8Mask) != 0;
                    UARTprintf("DIN in%d: %s\n", iInput, bOn ? "ON" : "OFF");
                    MQTTAppPublishInput(iInput, bOn);
                }
            }
        }
        pui8Prev[i] = pui8Cur[i];
    }
    bPrimed = true;
}

//*****************************************************************************
//
// Log DRV8860 nFAULT transitions (overcurrent / over-temperature / open-load).
//
//*****************************************************************************
static void
RelayFaultScan(void)
{
    static bool bPrevFault;
    bool bFault = RelayChainFault();

    if(bFault != bPrevFault)
    {
        UARTprintf("Relay nFAULT %s\n", bFault ? "ASSERTED" : "cleared");
        bPrevFault = bFault;
    }
}

//*****************************************************************************
//
// This application uses the Ethernet controller and lwIP TCP/IP stack to
// implement a web-configurable MQTT node.  Broker parameters are set via an
// on-board web page; the control board's field I/O is exposed over MQTT.
//
//*****************************************************************************
int
main(void)

{
    uint32_t ui32User0, ui32User1;
    uint8_t pui8MACArray[8];

    //
    // Make sure the main oscillator is enabled because this is required by
    // the PHY.  The system must have a 25MHz crystal attached to the OSC
    // pins.  The SYSCTL_MOSC_HIGHFREQ parameter is used when the crystal
    // frequency is 10MHz or higher.
    //
    SysCtlMOSCConfigSet(SYSCTL_MOSC_HIGHFREQ);

    //
    // Run from the PLL at 120 MHz.
    // Note: SYSCTL_CFG_VCO_240 is a new setting provided in TivaWare 2.2.x and
    // later to better reflect the actual VCO speed due to SYSCTL#22.
    //
    g_ui32SysClock = MAP_SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ |
                                             SYSCTL_OSC_MAIN |
                                             SYSCTL_USE_PLL |
                                             SYSCTL_CFG_VCO_240), 120000000);

    //
    // Configure the device pins.
    //
    PinoutSet(true, false);

    //
    // Configure debug port for internal use.
    //
    UARTStdioConfig(0, 115200, g_ui32SysClock);

    //
    // Clear the terminal and print a banner.
    //
    UARTprintf("\033[2J\033[H");
    UARTprintf("TM4C1294 MQTT IO\n\n");

    //
    // Load persistent MQTT configuration from EEPROM.
    //
    ConfigInit();

    //
    // Configure SysTick for a periodic interrupt.
    //
    MAP_SysTickPeriodSet(g_ui32SysClock / SYSTICKHZ);
    MAP_SysTickEnable();
    MAP_SysTickIntEnable();

    //
    // Configure the hardware MAC address for Ethernet Controller filtering of
    // incoming packets.  The MAC address will be stored in the non-volatile
    // USER0 and USER1 registers.
    //
    MAP_FlashUserGet(&ui32User0, &ui32User1);
    if((ui32User0 == 0xffffffff) || (ui32User1 == 0xffffffff))
    {
        //
        // Let the user know there is no MAC address
        //
        UARTprintf("No MAC programmed!\n");

        while(1)
        {
        }
    }

    //
    // Tell the user what we are doing just now.
    //
    UARTprintf("Waiting for IP.\n");

    //
    // Convert the 24/24 split MAC address from NV ram into a 32/16 split
    // MAC address needed to program the hardware registers, then program
    // the MAC address into the Ethernet Controller registers.
    //
    pui8MACArray[0] = ((ui32User0 >>  0) & 0xff);
    pui8MACArray[1] = ((ui32User0 >>  8) & 0xff);
    pui8MACArray[2] = ((ui32User0 >> 16) & 0xff);
    pui8MACArray[3] = ((ui32User1 >>  0) & 0xff);
    pui8MACArray[4] = ((ui32User1 >>  8) & 0xff);
    pui8MACArray[5] = ((ui32User1 >> 16) & 0xff);

    //
    // Initialize the lwIP library, using DHCP.
    //
    lwIPInit(g_ui32SysClock, pui8MACArray, 0, 0, 0, IPADDR_USE_DHCP);

    //
    // Setup the device locator service.
    //
    LocatorInit();
    LocatorMACAddrSet(pui8MACArray);
    LocatorAppTitleSet("EK-TM4C1294XL MQTT IO");

    //
    // Initialize a sample httpd server.
    //
    httpd_init();

    //
    // Set the interrupt priorities.  We set the SysTick interrupt to a higher
    // priority than the Ethernet interrupt to ensure that the file system
    // tick is processed if SysTick occurs while the Ethernet handler is being
    // processed.  This is very likely since all the TCP/IP and HTTP work is
    // done in the context of the Ethernet interrupt.
    //
    MAP_IntPrioritySet(INT_EMAC0, ETHERNET_INT_PRIORITY);
    MAP_IntPrioritySet(FAULT_SYSTICK, SYSTICK_INT_PRIORITY);

    //
    // Pass our tag information to the HTTP server.
    //
    http_set_ssi_handler((tSSIHandler)SSIHandler, g_pcConfigSSITags,
            NUM_CONFIG_SSI_TAGS);

    //
    // Pass our CGI handlers to the HTTP server.
    //
    http_set_cgi_handlers(g_psConfigCGIURIs, NUM_CONFIG_CGI_URIS);

    //
    // Initialize IO controls (legacy web-demo LED / animation timer).
    //
    io_init();

    //
    // Initialize the field-I/O chains with the configured device counts.  The
    // relay chain powers up with all relays off and outputs enabled.
    //
    DINChainInit(ConfigGetDinDevices());
    RelayChainInit(ConfigGetRelayDevices());
    UARTprintf("IO: %d input dev, %d relay dev.\n", ConfigGetDinDevices(),
               ConfigGetRelayDevices());

    //
    // Initialize the MQTT client subsystem (MAC seeds the HA device id).
    //
    MQTTAppInit(pui8MACArray);

    //
    // Main loop.  Networking (lwIP, httpd, MQTT receive) runs in interrupt
    // context; here we service the periodic application tick: apply pending
    // (re)connect requests and drive the MQTT keep-alive/reconnect timers.
    //
    while(1)
    {
        //
        // Wait for the next SysTick (~10 ms) application tick.
        //
        while(!g_bSysTickFlag)
        {
        }
        g_bSysTickFlag = false;

        //
        // Apply a pending (re)connect request from DHCP completion or a web
        // configuration change.
        //
        if(g_bStartMQTT)
        {
            g_bStartMQTT = false;
            //
            // A config change may also have altered the device counts.  Only
            // reconfigure the relay chain when its count actually changed, so an
            // unrelated setting change does not switch the relays off.
            //
            DINChainSetDevices(ConfigGetDinDevices());
            if(RelayChainGetDevices() != ConfigGetRelayDevices())
            {
                RelayChainSetDevices(ConfigGetRelayDevices());
            }
            MQTTAppStart();
        }

        //
        // Poll the input chain and the relay fault line; log any transitions.
        //
        DINChainScan();
        RelayFaultScan();

        //
        // Service MQTT keep-alive, reconnect timers and the post-connect
        // publish sequence.
        //
        MQTTAppTick(SYSTICKMS);
    }
}
