//*****************************************************************************
//
// enet_io.c - I/O control via a web server.
//
// Copyright (c) 2013-2020 Texas Instruments Incorporated.  All rights reserved.
// Software License Agreement
// 
// Texas Instruments (TI) is supplying this software for use solely and
// exclusively on TI's microcontroller products. The software is owned by
// TI and/or its suppliers, and is protected under applicable copyright
// laws. You may not combine this software with "viral" open-source
// software in order to form a larger program.
// 
// THIS SOFTWARE IS PROVIDED "AS IS" AND WITH ALL FAULTS.
// NO WARRANTIES, WHETHER EXPRESS, IMPLIED OR STATUTORY, INCLUDING, BUT
// NOT LIMITED TO, IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
// A PARTICULAR PURPOSE APPLY TO THIS SOFTWARE. TI SHALL NOT, UNDER ANY
// CIRCUMSTANCES, BE LIABLE FOR SPECIAL, INCIDENTAL, OR CONSEQUENTIAL
// DAMAGES, FOR ANY REASON WHATSOEVER.
// 
// This is part of revision 2.2.0.295 of the EK-TM4C1294XL Firmware Package.
//
//*****************************************************************************

#include <stdbool.h>
#include <stdint.h>
#include <string.h>
#include "inc/hw_ints.h"
#include "inc/hw_memmap.h"
#include "inc/hw_nvic.h"
#include "inc/hw_types.h"
#include "driverlib/flash.h"
#include "driverlib/gpio.h"
#include "driverlib/interrupt.h"
#include "driverlib/rom.h"
#include "driverlib/rom_map.h"
#include "driverlib/sysctl.h"
#include "driverlib/systick.h"
#include "driverlib/timer.h"
#include "utils/locator.h"
#include "utils/lwiplib.h"
#include "utils/uartstdio.h"
#include "utils/ustdlib.h"
#include "httpserver_raw/httpd.h"
#include "drivers/pinout.h"
#include "io.h"
#include "cgifuncs.h"
#include "config.h"
#include "mqtt_app.h"
#include "din_chain.h"
#include "relay_chain.h"
#include "input_events.h"
#include "relay_pulse.h"
#include "sntp_client.h"
#include "ota.h"

//*****************************************************************************
//
//! \addtogroup example_list
//! <h1>Ethernet-based I/O Control (enet_io)</h1>
//!
//! This example application demonstrates web-based I/O control using the
//! Tiva Ethernet controller and the lwIP TCP/IP Stack.  DHCP is used to
//! obtain an Ethernet address.  If DHCP times out without obtaining an
//! address, a static IP address will be chosen using AutoIP.  The address that
//! is selected will be shown on the UART allowing you to access the
//! internal web pages served by the application via your normal web browser.
//!
//! Two different methods of controlling board peripherals via web pages are
//! illustrated via pages labeled ``IO Control Demo 1'' and ``IO Control
//! Demo 2'' in the navigation menu on the left of the application's home page.
//! In both cases, the example allows you to toggle the state of the user LED
//! on the board and set the speed of a blinking LED.
//!
//! ``IO Control Demo 1'' uses JavaScript running in the web browser to send
//! HTTP requests for particular special URLs.  These special URLs are
//! intercepted in the file system support layer (io_fs.c) and used to
//! control the LED and animation LED.  Responses generated by the board are
//! returned to the browser and inserted into the page HTML dynamically by
//! more JavaScript code.
//!
//! ``IO Control Demo 2'' uses standard HTML forms to pass parameters to CGI
//! (Common Gateway Interface) handlers running on the board.  These handlers
//! process the form data and control the animation and LED as requested before
//! sending a response page (in this case, the original form) back to the
//! browser.  The application registers the names and handlers for each of its
//! CGIs with the HTTPD server during initialization and the server calls
//! these handlers after parsing URL parameters each time one of the CGI URLs
//! is requested.
//!
//! Information on the state of the various controls in the second demo is
//! inserted into the served HTML using SSI (Server Side Include) tags which
//! are parsed by the HTTPD server in the application.  As with the CGI
//! handlers, the application registers its list of SSI tags and a handler
//! function with the web server during initialization and this handler is
//! called whenever any registered tag is found in a .shtml, .ssi, .shtm or
//! .xml file being served to the browser.
//!
//! In addition to LED and animation speed control, the second example also
//! allows a line of text to be sent to the board for output to the UART.
//! This is included to illustrate the decoding of HTTP text strings.
//!
//! Note that the web server used by this example has been modified from the
//! example shipped with the basic lwIP package.  Additions include SSI and
//! CGI support along with the ability to have the server automatically insert
//! the HTTP headers rather than having these built in to the files in the
//! file system image.
//!
//! Source files for the internal file system image can be found in the ``fs''
//! directory.  If any of these files are changed, the file system image
//! (io_fsdata.h) should be rebuilt by running the following command from the
//! enet_io directory:
//!
//! ../../../../tools/bin/makefsfile -i fs -o io_fsdata.h -r -h -q
//!
//! For additional details on lwIP, refer to the lwIP web page at:
//! http://savannah.nongnu.org/projects/lwip/
//
//*****************************************************************************

//*****************************************************************************
//
// Defines for setting up the system clock.
//
//*****************************************************************************
#define SYSTICKHZ               100
#define SYSTICKMS               (1000 / SYSTICKHZ)

//*****************************************************************************
//
// Interrupt priority definitions.  The top 3 bits of these values are
// significant with lower values indicating higher priority interrupts.
//
//*****************************************************************************
#define SYSTICK_INT_PRIORITY    0x80
#define ETHERNET_INT_PRIORITY   0xC0

//*****************************************************************************
//
// A set of flags.  The flag bits are defined as follows:
//
//     0 -> An indicator that the animation timer interrupt has occurred.
//
//*****************************************************************************
#define FLAG_TICK            0
static volatile unsigned long g_ulFlags;

//*****************************************************************************
//
// External Application references.
//
//*****************************************************************************
extern void httpd_init(void);

//*****************************************************************************
//
// SSI tag indices for each entry in the g_pcSSITags array.
//
//*****************************************************************************
#define SSI_INDEX_HOST      0
#define SSI_INDEX_PORT      1
#define SSI_INDEX_CLIENT    2
#define SSI_INDEX_USER      3
#define SSI_INDEX_TOPIC     4
#define SSI_INDEX_AUTH      5
#define SSI_INDEX_STATUS    6
#define SSI_INDEX_IP        7
#define SSI_INDEX_DIN       8
#define SSI_INDEX_RELAY     9
#define SSI_INDEX_IOTYPES   10
#define SSI_INDEX_IOBINDS   11
#define SSI_INDEX_FWVER     12
#define SSI_INDEX_NTPTIME   13
#define SSI_INDEX_NTPSVR    14
#define SSI_INDEX_NTPTZ     15

//*****************************************************************************
//
// This array holds all the strings that are to be recognized as SSI tag
// names by the HTTPD server.  The server will call SSIHandler to request a
// replacement string whenever the pattern <!--#tagname--> (where tagname
// appears in the following array) is found in ".ssi", ".shtml" or ".shtm"
// files that it serves.
//
//*****************************************************************************
static const char *g_pcConfigSSITags[] =
{
    "mqhost",        // SSI_INDEX_HOST
    "mqport",        // SSI_INDEX_PORT
    "mqclient",      // SSI_INDEX_CLIENT
    "mquser",        // SSI_INDEX_USER
    "mqtopic",       // SSI_INDEX_TOPIC
    "mqauth",        // SSI_INDEX_AUTH
    "mqstatus",      // SSI_INDEX_STATUS
    "ipaddr",        // SSI_INDEX_IP
    "mqdin",         // SSI_INDEX_DIN
    "mqrelay",       // SSI_INDEX_RELAY
    "iotypes",       // SSI_INDEX_IOTYPES
    "iobinds",       // SSI_INDEX_IOBINDS
    "fwver",         // SSI_INDEX_FWVER  — build timestamp YYYYMMDDHHMM
    "ntptime",       // SSI_INDEX_NTPTIME — current time HH:MM:SS
    "ntpsvr",        // SSI_INDEX_NTPSVR  — NTP server hostname
    "ntptz"          // SSI_INDEX_NTPTZ   — UTC offset (signed integer)
};

//*****************************************************************************
//
// The number of individual SSI tags that the HTTPD server can expect to
// find in our configuration pages.
//
//*****************************************************************************
#define NUM_CONFIG_SSI_TAGS     (sizeof(g_pcConfigSSITags) / sizeof (char *))

//*****************************************************************************
//
// Prototypes for the various CGI handler functions.
//
//*****************************************************************************
static char *MQTTConfigCGIHandler(int32_t iIndex, int32_t i32NumParams,
                                  char *pcParam[], char *pcValue[]);
static char *IOConfigCGIHandler(int32_t iIndex, int32_t i32NumParams,
                                char *pcParam[], char *pcValue[]);
static char *FwChunkCGIHandler(int32_t iIndex, int32_t i32NumParams,
                               char *pcParam[], char *pcValue[]);
static char *FactoryResetCGIHandler(int32_t iIndex, int32_t i32NumParams,
                                    char *pcParam[], char *pcValue[]);
static char *NtpCfgCGIHandler(int32_t iIndex, int32_t i32NumParams,
                               char *pcParam[], char *pcValue[]);
static char *CfgRestoreCGIHandler(int32_t iIndex, int32_t i32NumParams,
                                  char *pcParam[], char *pcValue[]);

//*****************************************************************************
//
// Prototype for the main handler used to process server-side-includes for the
// application's web-based configuration screens.
//
//*****************************************************************************
static int32_t SSIHandler(int32_t iIndex, char *pcInsert, int32_t iInsertLen);

//*****************************************************************************
//
// CGI URI indices for each entry in the g_psConfigCGIURIs array.
//
//*****************************************************************************
#define CGI_INDEX_MQTTCFG       0
#define CGI_INDEX_IOCFG         1
#define CGI_INDEX_FWCHUNK       2
#define CGI_INDEX_FACTORYRESET  3
#define CGI_INDEX_NTPCFG        4
#define CGI_INDEX_CFGRESTORE    5

//*****************************************************************************
//
// This array is passed to the HTTPD server to inform it of special URIs
// that are treated as common gateway interface (CGI) scripts.  Each URI name
// is defined along with a pointer to the function which is to be called to
// process it.
//
//*****************************************************************************
static const tCGI g_psConfigCGIURIs[] =
{
    { "/mqttcfg.cgi",   (tCGIHandler)MQTTConfigCGIHandler }, // CGI_INDEX_MQTTCFG
    { "/iocfg.cgi",    (tCGIHandler)IOConfigCGIHandler   }, // CGI_INDEX_IOCFG
    { "/fwchunk.cgi",      (tCGIHandler)FwChunkCGIHandler      }, // CGI_INDEX_FWCHUNK
    { "/factoryreset.cgi",  (tCGIHandler)FactoryResetCGIHandler  }, // CGI_INDEX_FACTORYRESET
    { "/ntpcfg.cgi",       (tCGIHandler)NtpCfgCGIHandler        }, // CGI_INDEX_NTPCFG
    { "/cfgrestore.cgi",   (tCGIHandler)CfgRestoreCGIHandler     }  // CGI_INDEX_CFGRESTORE
};

//*****************************************************************************
//
// The number of individual CGI URIs that are configured for this system.
//
//*****************************************************************************
#define NUM_CONFIG_CGI_URIS     (sizeof(g_psConfigCGIURIs) / sizeof(tCGI))

//*****************************************************************************
//
// The file sent back to the browser by default following completion of any
// of our CGI handlers.  Each individual handler returns the URI of the page
// to load in response to it being called.
//
//*****************************************************************************
#define DEFAULT_CGI_RESPONSE    "/index.shtml"
#define IOCFG_CGI_RESPONSE      "/iocfg.shtml"

//*****************************************************************************
//
// The file sent back to the browser in cases where a parameter error is
// detected by one of the CGI handlers.  This should only happen if someone
// tries to access the CGI directly via the broswer command line and doesn't
// enter all the required parameters alongside the URI.
//
//*****************************************************************************
#define PARAM_ERROR_RESPONSE    "/perror.htm"

#define JAVASCRIPT_HEADER                                                     \
    "<script type='text/javascript' language='JavaScript'><!--\n"
#define JAVASCRIPT_FOOTER                                                     \
    "//--></script>\n"

//*****************************************************************************
//
// Timeout for DHCP address request (in seconds).
//
//*****************************************************************************
#ifndef DHCP_EXPIRE_TIMER_SECS
#define DHCP_EXPIRE_TIMER_SECS  45
#endif

//*****************************************************************************
//
// The current IP address.
//
//*****************************************************************************
uint32_t g_ui32IPAddress;

//*****************************************************************************
//
// MQTT IO integration state: a periodic tick flag set by SysTick, and a
// request flag asking the main loop to (re)start the MQTT connection (set
// when an IP is acquired or the configuration changes via the web UI).
//
//*****************************************************************************
static volatile bool g_bSysTickFlag;
static volatile bool g_bStartMQTT;
static volatile bool g_bRepublishMQTT;
static volatile bool g_bOTAReset;       // set by FwChunkCGIHandler on last chunk

//
// OTA upload state — written from the CGI handler (Ethernet ISR context).
//
static uint32_t g_ui32OTAWriteAddr;
static uint32_t g_ui32OTASize;
static uint8_t  g_ui8OTAAlignBuf[4];
static uint32_t g_ui32OTAAlignLen;
static uint32_t g_ui32OTALastErasedPage;

//*****************************************************************************
//
// The system clock frequency.  Used by the SD card driver.
//
//*****************************************************************************
uint32_t g_ui32SysClock;

//*****************************************************************************
//
// The error routine that is called if the driver library encounters an error.
//
//*****************************************************************************
#ifdef DEBUG
void
__error__(char *pcFilename, uint32_t ui32Line)
{
}
#endif

//*****************************************************************************
//
// Helper: copy a (possibly URL-encoded) CGI parameter into a fixed buffer.
//
//*****************************************************************************
static void
GetStringParam(const char *pcName, char *pcParam[], char *pcValue[],
               int32_t i32NumParams, char *pcDest, int32_t i32DestLen)
{
    int32_t i32Idx = FindCGIParameter(pcName, pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        DecodeFormString(pcValue[i32Idx], pcDest, i32DestLen);
    }
}

//*****************************************************************************
//
// CGI handler for /mqttcfg.cgi.  Parses the configuration form, stores the
// new settings in EEPROM and requests a reconnect.
//
//*****************************************************************************
static char *
MQTTConfigCGIHandler(int32_t iIndex, int32_t i32NumParams, char *pcParam[],
                     char *pcValue[])
{
    tMQTTConfig *psCfg = ConfigGet();
    int32_t i32Idx;

    (void)iIndex;

    //
    // String fields.  Empty values are accepted (e.g. to clear the host).
    //
    psCfg->pcHost[0] = '\0';
    GetStringParam("host", pcParam, pcValue, i32NumParams, psCfg->pcHost,
                   CFG_HOST_LEN);
    GetStringParam("client", pcParam, pcValue, i32NumParams, psCfg->pcClientID,
                   CFG_CLIENTID_LEN);
    GetStringParam("user", pcParam, pcValue, i32NumParams, psCfg->pcUser,
                   CFG_USER_LEN);
    GetStringParam("topic", pcParam, pcValue, i32NumParams, psCfg->pcTopicBase,
                   CFG_TOPIC_LEN);

    //
    // Password: only overwrite the stored value when a non-empty value is
    // submitted (the form never echoes the current password back).
    //
    i32Idx = FindCGIParameter("pass", pcParam, i32NumParams);
    if((i32Idx != -1) && (pcValue[i32Idx][0] != '\0'))
    {
        DecodeFormString(pcValue[i32Idx], psCfg->pcPass, CFG_PASS_LEN);
    }

    //
    // Port number.
    //
    i32Idx = FindCGIParameter("port", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        uint32_t ui32Port = ustrtoul(pcValue[i32Idx], 0, 10);
        psCfg->ui16Port = (ui32Port && (ui32Port <= 65535)) ?
                          (uint16_t)ui32Port : 1883;
    }

    //
    // Authentication checkbox (present in the form only when ticked).
    //
    psCfg->ui8UseAuth =
        (FindCGIParameter("auth", pcParam, i32NumParams) != -1) ? 1 : 0;

    //
    // Persist and ask the main loop to apply the new settings.
    //
    ConfigSave();
    g_bStartMQTT = true;

    return(DEFAULT_CGI_RESPONSE);
}

//*****************************************************************************
//
// Convert one ASCII hex character to its 4-bit value.
//
//*****************************************************************************
static uint8_t
HexNibble(char c)
{
    if((c >= '0') && (c <= '9'))
    {
        return((uint8_t)(c - '0'));
    }
    if((c >= 'a') && (c <= 'f'))
    {
        return((uint8_t)(c - 'a' + 10));
    }
    if((c >= 'A') && (c <= 'F'))
    {
        return((uint8_t)(c - 'A' + 10));
    }
    return(0);
}

//*****************************************************************************
//
// CGI handler for /iocfg.cgi.  Parses device counts and per-input type
// bitmask from the I/O configuration form, persists them to EEPROM and
// triggers a re-publish of HA discovery topics.
//
//*****************************************************************************
static char *
IOConfigCGIHandler(int32_t iIndex, int32_t i32NumParams, char *pcParam[],
                   char *pcValue[])
{
    int32_t i32Idx;

    (void)iIndex;

    //
    // Device counts.
    //
    i32Idx = FindCGIParameter("din", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        ConfigSetDinDevices((uint8_t)ustrtoul(pcValue[i32Idx], 0, 10));
    }
    i32Idx = FindCGIParameter("relay", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        ConfigSetRelayDevices((uint8_t)ustrtoul(pcValue[i32Idx], 0, 10));
    }

    //
    // Per-input type bitmask ("types" = hex string, 2 chars per byte of 8
    // inputs; bit n of byte b = input b*8+n is pushbutton when set).
    //
    i32Idx = FindCGIParameter("types", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        const char *pcT = pcValue[i32Idx];
        int iByte = 0;
        while((pcT[0] != '\0') && (pcT[1] != '\0') && (iByte < 15))
        {
            uint8_t ui8Val = (uint8_t)((HexNibble(pcT[0]) << 4) |
                                       HexNibble(pcT[1]));
            int iBit;
            for(iBit = 0; iBit < 8; iBit++)
            {
                ConfigSetInputPushbutton(iByte * 8 + iBit,
                                        (ui8Val & (1u << iBit)) != 0);
            }
            pcT += 2;
            iByte++;
        }
    }

    //
    // Per-input binding table: "binds" = 3 hex chars per slot, 4 slots per
    // input, for min(D*8, 16) inputs.  12-bit encoding: output[6:0]|act[4:3]|trig[2:0].
    // "000" = unused slot.
    //
    i32Idx = FindCGIParameter("binds", pcParam, i32NumParams);
    if(i32Idx != -1)
    {
        const char *pcB = pcValue[i32Idx];
        int iLen = (int)strlen(pcB);
        int iMaxIn = (int)ConfigGetDinDevices() * 8;
        int iInput, iSlot, iPos = 0;
        if(iMaxIn > 16) { iMaxIn = 16; }
        for(iInput = 0; (iInput < iMaxIn) && ((iPos + 2) < iLen); iInput++)
        {
            for(iSlot = 0; (iSlot < CFG_BIND_SLOTS) &&
                           ((iPos + 2) < iLen); iSlot++, iPos += 3)
            {
                uint16_t ui16V = (uint16_t)(((uint16_t)HexNibble(pcB[iPos]) << 8) |
                                            ((uint16_t)HexNibble(pcB[iPos+1]) << 4) |
                                             (uint16_t)HexNibble(pcB[iPos+2]));
                uint8_t ui8TrigAct = (uint8_t)(ui16V & 0x1Fu);
                uint8_t ui8Out     = (uint8_t)((ui16V >> 5) & 0x7Fu);
                if((ui8TrigAct & 0x07u) == 0)
                {
                    ui8TrigAct = 0;
                    ui8Out = BIND_OUTPUT_NONE;
                }
                ConfigBindingSet(iInput, iSlot, ui8TrigAct, ui8Out);
            }
        }
    }

    //
    // Persist all three records and request chain + discovery update.
    //
    ConfigSave();
    ConfigIOSave();
    ConfigBindingSave();
    g_bStartMQTT = true;
    g_bRepublishMQTT = true;

    return(IOCFG_CGI_RESPONSE);
}

//*****************************************************************************
//
// This function is called by the HTTP server whenever it encounters an SSI
// tag in a web page.  The iIndex parameter provides the index of the tag in
// the g_pcConfigSSITags array. This function writes the substitution text
// into the pcInsert array, writing no more than iInsertLen characters.
//
//*****************************************************************************
//*****************************************************************************
//
// FwChunkCGIHandler - Receives one hex-encoded binary chunk of an OTA image.
//
// URL format (GET):
//   /fwchunk.cgi?seq=N&last=0&data=HEXHEX...
//
// seq=0 initialises the upload and erases the header page + first image page.
// Each subsequent request appends to the staging flash.
// last=1 flushes the alignment buffer, computes CRC32, writes the OTA header
// and EEPROM flag, then schedules a system reset.
//
// The hex-encoded payload carries up to ~494 binary bytes per request
// (limited by LWIP_HTTPD_MAX_URI_LEN = 1024).
//
//*****************************************************************************
static char *
FwChunkCGIHandler(int32_t iIndex, int32_t i32NumParams,
                  char *pcParam[], char *pcValue[])
{
    int32_t  iSeqIdx, iLastIdx, iDataIdx;
    int32_t  iSeqNum;
    bool     bLast;
    const char *pcData;
    uint32_t ui32DataHexLen, i;
    uint32_t ui32PageAddr;
    tOTAHeader sHdr;
    uint32_t ui32Crc;

    iSeqIdx  = FindCGIParameter("seq",  pcParam, i32NumParams);
    iLastIdx = FindCGIParameter("last", pcParam, i32NumParams);
    iDataIdx = FindCGIParameter("data", pcParam, i32NumParams);

    if(iSeqIdx < 0 || iDataIdx < 0)
    {
        return(DEFAULT_CGI_RESPONSE);
    }

    iSeqNum = (int32_t)ustrtoul(pcValue[iSeqIdx], NULL, 10);
    bLast   = (iLastIdx >= 0) && (pcValue[iLastIdx][0] == '1');
    pcData  = pcValue[iDataIdx];
    ui32DataHexLen = ustrlen(pcData) & ~1u; // must be even (pairs of hex chars)

    //
    // First chunk: reset state and pre-erase the header and first image page.
    //
    if(iSeqNum == 0)
    {
        g_ui32OTAWriteAddr    = OTA_IMAGE_ADDR;
        g_ui32OTASize         = 0;
        g_ui32OTAAlignLen     = 0;
        g_ui32OTALastErasedPage = OTA_IMAGE_ADDR;

        MAP_FlashErase(OTA_HEADER_ADDR);
        MAP_FlashErase(OTA_IMAGE_ADDR);

        UARTprintf("OTA: upload started.\n");
    }

    //
    // Decode hex bytes and write to staging flash in 4-byte aligned words.
    //
    for(i = 0; i < ui32DataHexLen; i += 2)
    {
        g_ui8OTAAlignBuf[g_ui32OTAAlignLen++] =
            (uint8_t)((HexNibble(pcData[i]) << 4) | HexNibble(pcData[i + 1]));
        g_ui32OTASize++;

        if(g_ui32OTAAlignLen == 4)
        {
            //
            // Erase the next 16 KB page when the write pointer first enters it.
            //
            ui32PageAddr = g_ui32OTAWriteAddr & ~(0x4000u - 1u);
            if(ui32PageAddr > g_ui32OTALastErasedPage)
            {
                MAP_FlashErase(ui32PageAddr);
                g_ui32OTALastErasedPage = ui32PageAddr;
            }

            MAP_FlashProgram((uint32_t *)(uintptr_t)g_ui8OTAAlignBuf,
                             g_ui32OTAWriteAddr, 4);
            g_ui32OTAWriteAddr += 4;
            g_ui32OTAAlignLen   = 0;
        }
    }

    //
    // Last chunk: flush any partial word (pad with 0xFF), then finalise.
    //
    if(bLast)
    {
        if(g_ui32OTAAlignLen > 0)
        {
            while(g_ui32OTAAlignLen < 4)
            {
                g_ui8OTAAlignBuf[g_ui32OTAAlignLen++] = 0xFF;
            }
            MAP_FlashProgram((uint32_t *)(uintptr_t)g_ui8OTAAlignBuf,
                             g_ui32OTAWriteAddr, 4);
            g_ui32OTAWriteAddr += 4;
            g_ui32OTAAlignLen   = 0;
        }

        //
        // CRC32 the staged image and write the header to 0x80000.
        //
        ui32Crc = ConfigCRC32((const uint8_t *)OTA_IMAGE_ADDR, g_ui32OTASize);

        sHdr.ui32Magic = OTA_HDR_MAGIC;
        sHdr.ui32Size  = g_ui32OTASize;
        sHdr.ui32CRC32 = ui32Crc;
        sHdr.ui32Rsvd  = 0;
        MAP_FlashProgram((uint32_t *)(uintptr_t)&sHdr,
                         OTA_HEADER_ADDR, sizeof(tOTAHeader));

        //
        // Set EEPROM pending flag so the next boot applies the update.
        //
        OtaSetPending(g_ui32OTASize);

        UARTprintf("OTA: %u bytes, CRC=0x%08x. Rebooting...\n",
                   g_ui32OTASize, ui32Crc);

        //
        // Signal the main loop to reset after the HTTP response is sent.
        //
        g_bOTAReset = true;
        return("/fwupdate_ok.shtml");
    }

    return("/fwupdate.shtml");
}

//*****************************************************************************
//
// FactoryResetCGIHandler - Web-triggered factory reset.
//
// Invalidates all EEPROM records, then schedules a system reset via the same
// g_bOTAReset flag used by the OTA handler so the HTTP response is sent first.
//
//*****************************************************************************
static char *
FactoryResetCGIHandler(int32_t iIndex, int32_t i32NumParams,
                       char *pcParam[], char *pcValue[])
{
    UARTprintf("Factory reset triggered via web UI.\n");
    MQTTAppStop();
    ConfigFactoryReset();
    g_bOTAReset = true;
    return("/factoryreset_ok.shtml");
}

//*****************************************************************************
//
// CheckHWFactoryReset - Check SW1 (PJ0) at startup.
//
// If SW1 is held continuously for 5 seconds, all EEPROM records are
// invalidated and the device resets.  LED D1 (PN1) blinks as a countdown
// indicator.  Releasing SW1 at any point cancels the operation.
//
// Call after ConfigInit() (EEPROM must be initialised) but before the
// network stack starts.
//
//*****************************************************************************
static void
CheckHWFactoryReset(void)
{
    uint32_t ui32Count;

    //
    // Enable the GPIO ports used by SW1 (Port J) and LED D1 (Port N).
    // PinoutSet() may already have done this, but enabling twice is harmless.
    //
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOJ);
    MAP_SysCtlPeripheralEnable(SYSCTL_PERIPH_GPION);
    while(!MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_GPIOJ) ||
          !MAP_SysCtlPeripheralReady(SYSCTL_PERIPH_GPION))
    {
    }

    //
    // PJ0 input with weak pull-up (SW1 is active-low).
    //
    MAP_GPIODirModeSet(GPIO_PORTJ_BASE, GPIO_PIN_0, GPIO_DIR_MODE_IN);
    MAP_GPIOPadConfigSet(GPIO_PORTJ_BASE, GPIO_PIN_0,
                         GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD_WPU);

    //
    // PN1 output for LED D1 (active-high, off initially).
    //
    MAP_GPIODirModeSet(GPIO_PORTN_BASE, GPIO_PIN_1, GPIO_DIR_MODE_OUT);
    MAP_GPIOPadConfigSet(GPIO_PORTN_BASE, GPIO_PIN_1,
                         GPIO_STRENGTH_2MA, GPIO_PIN_TYPE_STD);
    MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, 0);

    //
    // Quick exit if SW1 is not held at boot.
    //
    if(MAP_GPIOPinRead(GPIO_PORTJ_BASE, GPIO_PIN_0) != 0)
    {
        return;
    }

    UARTprintf("HW factory reset: keep SW1 held for 5s to confirm...\n");

    //
    // 500 x 10ms = 5 000ms countdown.  LED blinks every 500ms.
    //
    for(ui32Count = 0; ui32Count < 500; ui32Count++)
    {
        //
        // Toggle LED every 50 iterations (~500ms period).
        //
        MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1,
                         ((ui32Count / 50) & 1) ? GPIO_PIN_1 : 0);

        MAP_SysCtlDelay(g_ui32SysClock / 300);   // ~10 ms at 120 MHz

        if(MAP_GPIOPinRead(GPIO_PORTJ_BASE, GPIO_PIN_0) != 0)
        {
            MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, 0);
            UARTprintf("HW factory reset: cancelled (SW1 released).\n");
            return;
        }
    }

    //
    // SW1 held for 5 seconds — perform factory reset.
    //
    MAP_GPIOPinWrite(GPIO_PORTN_BASE, GPIO_PIN_1, GPIO_PIN_1); // LED on solid
    UARTprintf("HW factory reset: erasing EEPROM...\n");
    MQTTAppStop();
    ConfigFactoryReset();
    UARTprintf("HW factory reset: rebooting...\n");
    MAP_SysCtlDelay(g_ui32SysClock / 3);
    MAP_SysCtlReset();
}

//*****************************************************************************
//
// NtpCfgCGIHandler - Save NTP server + TZ offset then restart SNTP.
//
//*****************************************************************************
static char *
NtpCfgCGIHandler(int32_t iIndex, int32_t i32NumParams,
                 char *pcParam[], char *pcValue[])
{
    int32_t iIdx;
    char    acServer[CFG_NTP_SERVER_LEN];
    int32_t i32Tz = 0;

    iIdx = FindCGIParameter("ntp", pcParam, i32NumParams);
    if(iIdx >= 0)
    {
        GetStringParam("ntp", pcParam, pcValue, i32NumParams,
                       acServer, CFG_NTP_SERVER_LEN);
        ConfigNtpSetServer(acServer);
    }

    iIdx = FindCGIParameter("tz", pcParam, i32NumParams);
    if(iIdx >= 0)
    {
        i32Tz = (int32_t)ustrtoul(pcValue[iIdx], NULL, 10);
        if(pcValue[iIdx][0] == '-') { i32Tz = -i32Tz; }
        if(i32Tz < -12) { i32Tz = -12; }
        if(i32Tz >  14) { i32Tz =  14; }
        ConfigNtpSetTz((int8_t)i32Tz);
    }

    ConfigNtpSave();
    SntpInit();
    UARTprintf("NTP: config updated, re-syncing.\n");
    return(DEFAULT_CGI_RESPONSE);
}

//*****************************************************************************
//
// CfgRestoreCGIHandler - Restore broker + NTP config from a JSON chunk stream.
//
// URL: /cfgrestore.cgi?seq=N&last=0|1&data=HEXHEX...
//
// Hex-decoded bytes accumulate in g_acCfgRestoreBuf.  On last=1 the buffer
// is parsed as JSON and the broker + NTP EEPROM records are updated.
//
//*****************************************************************************
#define CFG_RESTORE_BUF_SIZE 1024

static char    g_acCfgRestoreBuf[CFG_RESTORE_BUF_SIZE];
static uint32_t g_ui32CfgRestoreLen = 0;

//
// Minimal JSON value extractor using strstr.
//
static bool
CfgJsonGetStr(const char *pcJson, const char *pcKey,
              char *pcVal, int iMax)
{
    char acSearch[48];
    const char *p;
    int i = 0;
    usnprintf(acSearch, sizeof(acSearch), "\"%s\":\"", pcKey);
    p = strstr(pcJson, acSearch);
    if(!p) { return(false); }
    p += ustrlen(acSearch);
    while(*p && *p != '"' && i < iMax - 1) { pcVal[i++] = *p++; }
    pcVal[i] = '\0';
    return(true);
}

static int32_t
CfgJsonGetInt(const char *pcJson, const char *pcKey)
{
    char acSearch[48];
    const char *p;
    usnprintf(acSearch, sizeof(acSearch), "\"%s\":", pcKey);
    p = strstr(pcJson, acSearch);
    if(!p) { return(-1); }
    p += ustrlen(acSearch);
    if(*p == '-') { return(-(int32_t)ustrtoul(p + 1, NULL, 10)); }
    return((int32_t)ustrtoul(p, NULL, 10));
}

static char *
CfgRestoreCGIHandler(int32_t iIndex, int32_t i32NumParams,
                     char *pcParam[], char *pcValue[])
{
    int32_t iSeqIdx, iLastIdx, iDataIdx;
    bool    bLast;
    const char *pcData;
    uint32_t ui32DataHexLen, i;

    iSeqIdx  = FindCGIParameter("seq",  pcParam, i32NumParams);
    iLastIdx = FindCGIParameter("last", pcParam, i32NumParams);
    iDataIdx = FindCGIParameter("data", pcParam, i32NumParams);

    if(iSeqIdx < 0 || iDataIdx < 0) { return(DEFAULT_CGI_RESPONSE); }

    bLast  = (iLastIdx >= 0) && (pcValue[iLastIdx][0] == '1');
    pcData = pcValue[iDataIdx];
    ui32DataHexLen = ustrlen(pcData) & ~1u;

    if(ustrtoul(pcValue[iSeqIdx], NULL, 10) == 0)
    {
        g_ui32CfgRestoreLen = 0;
    }

    for(i = 0; i < ui32DataHexLen && g_ui32CfgRestoreLen < CFG_RESTORE_BUF_SIZE - 1u; i += 2)
    {
        g_acCfgRestoreBuf[g_ui32CfgRestoreLen++] =
            (char)((HexNibble(pcData[i]) << 4) | HexNibble(pcData[i + 1]));
    }

    if(!bLast) { return(DEFAULT_CGI_RESPONSE); }

    g_acCfgRestoreBuf[g_ui32CfgRestoreLen] = '\0';
    UARTprintf("CfgRestore: %u bytes JSON received.\n", g_ui32CfgRestoreLen);

    //
    // Parse and apply broker config.
    //
    {
        tMQTTConfig *psCfg = ConfigGet();
        char        acTmp[64];
        int32_t     i32Val;

        if(CfgJsonGetStr(g_acCfgRestoreBuf, "host", acTmp, CFG_HOST_LEN))
        { ustrncpy(psCfg->pcHost, acTmp, CFG_HOST_LEN - 1); }
        if(CfgJsonGetStr(g_acCfgRestoreBuf, "client", acTmp, CFG_CLIENTID_LEN))
        { ustrncpy(psCfg->pcClientID, acTmp, CFG_CLIENTID_LEN - 1); }
        if(CfgJsonGetStr(g_acCfgRestoreBuf, "user", acTmp, CFG_USER_LEN))
        { ustrncpy(psCfg->pcUser, acTmp, CFG_USER_LEN - 1); }
        if(CfgJsonGetStr(g_acCfgRestoreBuf, "topic", acTmp, CFG_TOPIC_LEN))
        { ustrncpy(psCfg->pcTopicBase, acTmp, CFG_TOPIC_LEN - 1); }
        i32Val = CfgJsonGetInt(g_acCfgRestoreBuf, "port");
        if(i32Val > 0 && i32Val <= 65535) { psCfg->ui16Port = (uint16_t)i32Val; }
        i32Val = CfgJsonGetInt(g_acCfgRestoreBuf, "auth");
        if(i32Val >= 0) { psCfg->ui8UseAuth = (uint8_t)(i32Val != 0); }
        i32Val = CfgJsonGetInt(g_acCfgRestoreBuf, "din");
        if(i32Val > 0) { ConfigSetDinDevices((uint8_t)i32Val); }
        i32Val = CfgJsonGetInt(g_acCfgRestoreBuf, "relay");
        if(i32Val > 0) { ConfigSetRelayDevices((uint8_t)i32Val); }
        ConfigSave();
    }

    //
    // Parse and apply NTP config.
    //
    {
        char    acTmp[CFG_NTP_SERVER_LEN];
        int32_t i32Val;
        if(CfgJsonGetStr(g_acCfgRestoreBuf, "ntp", acTmp, CFG_NTP_SERVER_LEN))
        { ConfigNtpSetServer(acTmp); }
        i32Val = CfgJsonGetInt(g_acCfgRestoreBuf, "tz");
        if(i32Val >= -12 && i32Val <= 14) { ConfigNtpSetTz((int8_t)i32Val); }
        ConfigNtpSave();
    }

    UARTprintf("CfgRestore: settings applied. Rebooting...\n");
    g_bOTAReset = true;
    return("/cfgrestore_ok.shtml");
}

//*****************************************************************************
static int32_t
SSIHandler(int32_t iIndex, char *pcInsert, int32_t iInsertLen)
{
    tMQTTConfig *psCfg = ConfigGet();

    //
    // Which SSI tag have we been passed?  (The password is intentionally never
    // echoed back to the browser.)
    //
    switch(iIndex)
    {
        case SSI_INDEX_HOST:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcHost);
            break;

        case SSI_INDEX_PORT:
            usnprintf(pcInsert, iInsertLen, "%d", psCfg->ui16Port);
            break;

        case SSI_INDEX_CLIENT:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcClientID);
            break;

        case SSI_INDEX_USER:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcUser);
            break;

        case SSI_INDEX_TOPIC:
            usnprintf(pcInsert, iInsertLen, "%s", psCfg->pcTopicBase);
            break;

        case SSI_INDEX_DIN:
            usnprintf(pcInsert, iInsertLen, "%d", ConfigGetDinDevices());
            break;

        case SSI_INDEX_RELAY:
            usnprintf(pcInsert, iInsertLen, "%d", ConfigGetRelayDevices());
            break;

        case SSI_INDEX_AUTH:
            usnprintf(pcInsert, iInsertLen, "%s",
                      psCfg->ui8UseAuth ? "checked" : "");
            break;

        case SSI_INDEX_STATUS:
            usnprintf(pcInsert, iInsertLen, "%s", MQTTAppStatusStr());
            break;

        case SSI_INDEX_IP:
            usnprintf(pcInsert, iInsertLen, "%d.%d.%d.%d",
                      g_ui32IPAddress & 0xff, (g_ui32IPAddress >> 8) & 0xff,
                      (g_ui32IPAddress >> 16) & 0xff,
                      (g_ui32IPAddress >> 24) & 0xff);
            break;

        case SSI_INDEX_IOTYPES:
        {
            //
            // Emit one byte (2 hex chars) per DIN device, LSB = input 0 of
            // that device.  The I/O config page uses this to seed each select.
            //
            static const char pcHex[] = "0123456789abcdef";
            int iDin = (int)ConfigGetDinDevices();
            int iByte, iBit;
            int iPos = 0;
            for(iByte = 0; (iByte < iDin) && ((iPos + 2) < iInsertLen);
                iByte++)
            {
                uint8_t ui8Val = 0;
                for(iBit = 0; iBit < 8; iBit++)
                {
                    if(ConfigInputIsPushbutton(iByte * 8 + iBit))
                    {
                        ui8Val |= (uint8_t)(1u << iBit);
                    }
                }
                pcInsert[iPos++] = pcHex[(ui8Val >> 4) & 0xF];
                pcInsert[iPos++] = pcHex[ui8Val & 0xF];
            }
            pcInsert[iPos] = '\0';
            break;
        }

        case SSI_INDEX_IOBINDS:
        {
            //
            // Emit min(D*8, 16) inputs x 4 slots x 3 hex chars = up to 192 chars.
            // Per slot: 12-bit value = (output<<5)|(action<<3)|trigger as "XYZ".
            // "000" = unused slot.
            //
            static const char pcHexB[] = "0123456789abcdef";
            int iDin = (int)ConfigGetDinDevices();
            int iMaxIn = iDin * 8;
            int iInput, iSlot, iPos = 0;
            if(iMaxIn > 16) { iMaxIn = 16; }
            for(iInput = 0; (iInput < iMaxIn) && ((iPos + 3) < iInsertLen);
                iInput++)
            {
                for(iSlot = 0; (iSlot < CFG_BIND_SLOTS) &&
                               ((iPos + 3) < iInsertLen); iSlot++)
                {
                    uint8_t ta  = ConfigBindingGetTrigAct(iInput, iSlot);
                    uint8_t out = ConfigBindingGetOutput(iInput, iSlot);
                    uint16_t v  = 0;
                    if(((ta & 0x07u) != 0) && (out != BIND_OUTPUT_NONE))
                    {
                        v = (uint16_t)(((uint16_t)out << 5) | (ta & 0x1Fu));
                    }
                    pcInsert[iPos++] = pcHexB[(v >> 8) & 0xFu];
                    pcInsert[iPos++] = pcHexB[(v >> 4) & 0xFu];
                    pcInsert[iPos++] = pcHexB[v & 0xFu];
                }
            }
            pcInsert[iPos] = '\0';
            break;
        }

        case SSI_INDEX_FWVER:
        {
            //
            // Build timestamp formatted as YYYYMMDDHHMM from __DATE__ and
            // __TIME__ (both are compile-time string literals).
            //
            // __DATE__ = "Mon DD YYYY"  e.g. "Jul 11 2026"  (space-padded day)
            // __TIME__ = "HH:MM:SS"     e.g. "09:23:45"
            //
            static const char pcMons[] =
                "JanFebMarAprMayJunJulAugSepOctNovDec";
            const char *pd = __DATE__;
            const char *pt = __TIME__;
            int iMon, iDay, iYear, iHour, iMin;

            for(iMon = 0; iMon < 12; iMon++)
            {
                if((pd[0] == pcMons[iMon * 3]) &&
                   (pd[1] == pcMons[iMon * 3 + 1]) &&
                   (pd[2] == pcMons[iMon * 3 + 2]))
                {
                    break;
                }
            }
            iMon++;
            iDay  = ((pd[4] == ' ') ? 0 : (pd[4] - '0')) * 10 + (pd[5] - '0');
            iYear = (pd[7]-'0')*1000 + (pd[8]-'0')*100 +
                    (pd[9]-'0')*10   + (pd[10]-'0');
            iHour = (pt[0]-'0')*10 + (pt[1]-'0');
            iMin  = (pt[3]-'0')*10 + (pt[4]-'0');

            usnprintf(pcInsert, iInsertLen, "%04d%02d%02d%02d%02d",
                      iYear, iMon, iDay, iHour, iMin);
            break;
        }

        case SSI_INDEX_NTPTIME:
            SntpGetTimeStr(pcInsert, iInsertLen);
            break;

        case SSI_INDEX_NTPSVR:
            usnprintf(pcInsert, iInsertLen, "%s",
                      ConfigNtpGet()->pcServer);
            break;

        case SSI_INDEX_NTPTZ:
            usnprintf(pcInsert, iInsertLen, "%d",
                      (int)ConfigNtpGet()->i8TzOffset);
            break;

        default:
            usnprintf(pcInsert, iInsertLen, "??");
            break;
    }

    //
    // Tell the server how many characters our insert string contains.
    //
    return(strlen(pcInsert));
}

//*****************************************************************************
//
// The interrupt handler for the SysTick interrupt.
//
//*****************************************************************************
void
SysTickIntHandler(void)
{
    //
    // Call the lwIP timer handler.
    //
    lwIPTimer(SYSTICKMS);

    //
    // Flag a periodic application tick for the main loop (MQTT keep-alive /
    // reconnect service).
    //
    g_bSysTickFlag = true;
}

//*****************************************************************************
//
// The interrupt handler for the timer used to pace the animation.
//
//*****************************************************************************
void
AnimTimerIntHandler(void)
{
    //
    // Clear the timer interrupt.
    //
    MAP_TimerIntClear(TIMER2_BASE, TIMER_TIMA_TIMEOUT);

    //
    // Indicate that a timer interrupt has occurred.
    //
    HWREGBITW(&g_ulFlags, FLAG_TICK) = 1;
}

//*****************************************************************************
//
// Display an lwIP type IP Address.
//
//*****************************************************************************
void
DisplayIPAddress(uint32_t ui32Addr)
{
    char pcBuf[16];

    //
    // Convert the IP Address into a string.
    //
    usprintf(pcBuf, "%d.%d.%d.%d", ui32Addr & 0xff, (ui32Addr >> 8) & 0xff,
            (ui32Addr >> 16) & 0xff, (ui32Addr >> 24) & 0xff);

    //
    // Display the string.
    //
    UARTprintf(pcBuf);
}

//*****************************************************************************
//
// Required by lwIP library to support any host-related timer functions.
//
//*****************************************************************************
void
lwIPHostTimerHandler(void)
{
    uint32_t ui32NewIPAddress;

    //
    // Get the current IP address.
    //
    ui32NewIPAddress = lwIPLocalIPAddrGet();

    //
    // See if the IP address has changed.
    //
    if(ui32NewIPAddress != g_ui32IPAddress)
    {
        //
        // See if there is an IP address assigned.
        //
        if(ui32NewIPAddress == 0xffffffff)
        {
            //
            // Indicate that there is no link.
            //
            UARTprintf("Waiting for link.\n");
        }
        else if(ui32NewIPAddress == 0)
        {
            //
            // There is no IP address, so indicate that the DHCP process is
            // running.
            //
            UARTprintf("Waiting for IP address.\n");
        }
        else
        {
            //
            // Display the new IP address.
            //
            UARTprintf("IP Address: ");
            DisplayIPAddress(ui32NewIPAddress);
            UARTprintf("\n");
            UARTprintf("Open a browser and enter the IP address.\n");

            //
            // We now have network connectivity: ask the main loop to bring up
            // the MQTT connection (if a broker has been configured).
            //
            g_bStartMQTT = true;
            SntpInit();
        }

        //
        // Save the new IP address.
        //
        g_ui32IPAddress = ui32NewIPAddress;
    }

    //
    // If there is not an IP address.
    //
    if((ui32NewIPAddress == 0) || (ui32NewIPAddress == 0xffffffff))
    {
        //
        // Do nothing and keep waiting.
        //
    }
}

//*****************************************************************************
//
// Apply all binding slots for one input that match the given trigger event.
// Each matching slot sets a relay and publishes its new retained state.
//
//*****************************************************************************
static void
ApplyBindings(int iInput, uint8_t ui8Trig)
{
    int iSlot;

    for(iSlot = 0; iSlot < CFG_BIND_SLOTS; iSlot++)
    {
        uint8_t ta  = ConfigBindingGetTrigAct(iInput, iSlot);
        uint8_t out = ConfigBindingGetOutput(iInput, iSlot);
        uint8_t trig = ta & 0x07u;
        uint8_t act  = (ta >> 3) & 0x03u;
        bool bOn;

        if((trig != ui8Trig) || (out == BIND_OUTPUT_NONE) ||
           (out >= (uint8_t)RelayChainCount()))
        {
            continue;
        }

        if(act == BIND_ACT_ON)
        {
            bOn = true;
        }
        else if(act == BIND_ACT_OFF)
        {
            bOn = false;
        }
        else
        {
            bOn = !RelayChainGet(out);
        }

        UARTprintf("Bind: in%d trig%d -> relay%d %s\n",
                   iInput, ui8Trig, out, bOn ? "ON" : "OFF");
        MQTTAppSetRelay(out, bOn);
    }
}

//*****************************************************************************
//
// Click-event callback: publish the HA event and apply any binding.
//
//*****************************************************************************
static void
IEClickCallback(int iInput, const char *pcEvt)
{
    uint8_t ui8Trig;

    MQTTAppPublishInputEvent(iInput, pcEvt);

    ui8Trig = (pcEvt[0] == 's') ? BIND_TRIG_SINGLE : BIND_TRIG_DOUBLE;
    ApplyBindings(iInput, ui8Trig);
}

//*****************************************************************************
//
// Poll the SN65HVS882 input chain and log any change over UART.  Called from
// the periodic application tick.  This is bring-up instrumentation - MQTT
// publishing of the inputs will hook in here next.
//
//*****************************************************************************
static void
DINChainScan(void)
{
    static uint8_t pui8Prev[DIN_MAX_BYTES];
    static bool bPrimed;
    uint8_t pui8Cur[DIN_MAX_BYTES];
    uint8_t ui8Bytes, i;

    ui8Bytes = DINChainRead(pui8Cur, sizeof(pui8Cur));
    if(ui8Bytes == 0)
    {
        return;
    }

    //
    // Process each input.  Channel c of device d maps to bit (7-c) of byte d
    // and to input index d*8+c.
    //
    // Pushbutton inputs: feed the current level to the click-detector every
    // scan (the FSM needs a continuous level signal for debounce).
    //
    // Switch inputs: detect edges vs the previous scan and publish ON/OFF.
    // The first scan only primes the baseline; initial retained states are
    // published by the MQTT post-connect sequence.
    //
    for(i = 0; i < ui8Bytes; i++)
    {
        uint8_t ui8Diff = (uint8_t)(pui8Cur[i] ^ pui8Prev[i]);
        int iBit;

        for(iBit = 0; iBit < 8; iBit++)
        {
            uint8_t ui8Mask = (uint8_t)(0x80 >> iBit);
            int iInput = (i * 8) + iBit;
            bool bActive = (pui8Cur[i] & ui8Mask) != 0;

            if(ConfigInputIsPushbutton(iInput))
            {
                InputEventsUpdate(iInput, bActive);
            }
            else if(bPrimed && (ui8Diff & ui8Mask))
            {
                UARTprintf("DIN in%d: %s\n", iInput, bActive ? "ON" : "OFF");
                MQTTAppPublishInput(iInput, bActive);
                ApplyBindings(iInput,
                              bActive ? BIND_TRIG_LEVEL_ON : BIND_TRIG_LEVEL_OFF);
            }
        }
        pui8Prev[i] = pui8Cur[i];
    }
    bPrimed = true;
}

//*****************************************************************************
//
// Log DRV8860 nFAULT transitions (overcurrent / over-temperature / open-load).
//
//*****************************************************************************
static void
RelayFaultScan(void)
{
    static bool bPrevFault;
    bool bFault = RelayChainFault();

    if(bFault != bPrevFault)
    {
        UARTprintf("Relay nFAULT %s\n", bFault ? "ASSERTED" : "cleared");
        bPrevFault = bFault;
    }
}

//*****************************************************************************
//
// This application uses the Ethernet controller and lwIP TCP/IP stack to
// implement a web-configurable MQTT node.  Broker parameters are set via an
// on-board web page; the control board's field I/O is exposed over MQTT.
//
//*****************************************************************************
int
main(void)

{
    uint32_t ui32User0, ui32User1;
    uint8_t pui8MACArray[8];

    //
    // Make sure the main oscillator is enabled because this is required by
    // the PHY.  The system must have a 25MHz crystal attached to the OSC
    // pins.  The SYSCTL_MOSC_HIGHFREQ parameter is used when the crystal
    // frequency is 10MHz or higher.
    //
    SysCtlMOSCConfigSet(SYSCTL_MOSC_HIGHFREQ);

    //
    // Run from the PLL at 120 MHz.
    // Note: SYSCTL_CFG_VCO_240 is a new setting provided in TivaWare 2.2.x and
    // later to better reflect the actual VCO speed due to SYSCTL#22.
    //
    g_ui32SysClock = MAP_SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ |
                                             SYSCTL_OSC_MAIN |
                                             SYSCTL_USE_PLL |
                                             SYSCTL_CFG_VCO_240), 120000000);

    //
    // Configure the device pins.
    //
    PinoutSet(true, false);

    //
    // Configure debug port for internal use.
    //
    UARTStdioConfig(0, 115200, g_ui32SysClock);

    //
    // Clear the terminal and print a banner.
    //
    UARTprintf("\033[2J\033[H");
    UARTprintf("TM4C1294 MQTT IO\n\n");

    //
    // Load persistent MQTT configuration from EEPROM.
    //
    ConfigInit();

    //
    // If a firmware update was staged before the last reset, validate it and
    // apply it now (OtaCheckAndApply calls OtaApply which never returns).
    //
    OtaCheckAndApply();

    //
    // Check if SW1 (PJ0) is held at boot for a hardware factory reset.
    // If held for 5 s, EEPROM is erased and the device resets.
    //
    CheckHWFactoryReset();

    //
    // Configure SysTick for a periodic interrupt.
    //
    MAP_SysTickPeriodSet(g_ui32SysClock / SYSTICKHZ);
    MAP_SysTickEnable();
    MAP_SysTickIntEnable();

    //
    // Configure the hardware MAC address for Ethernet Controller filtering of
    // incoming packets.  The MAC address will be stored in the non-volatile
    // USER0 and USER1 registers.
    //
    MAP_FlashUserGet(&ui32User0, &ui32User1);
    if((ui32User0 == 0xffffffff) || (ui32User1 == 0xffffffff))
    {
        //
        // Let the user know there is no MAC address
        //
        UARTprintf("No MAC programmed!\n");

        while(1)
        {
        }
    }

    //
    // Tell the user what we are doing just now.
    //
    UARTprintf("Waiting for IP.\n");

    //
    // Convert the 24/24 split MAC address from NV ram into a 32/16 split
    // MAC address needed to program the hardware registers, then program
    // the MAC address into the Ethernet Controller registers.
    //
    pui8MACArray[0] = ((ui32User0 >>  0) & 0xff);
    pui8MACArray[1] = ((ui32User0 >>  8) & 0xff);
    pui8MACArray[2] = ((ui32User0 >> 16) & 0xff);
    pui8MACArray[3] = ((ui32User1 >>  0) & 0xff);
    pui8MACArray[4] = ((ui32User1 >>  8) & 0xff);
    pui8MACArray[5] = ((ui32User1 >> 16) & 0xff);

    //
    // Initialize the lwIP library, using DHCP.
    //
    lwIPInit(g_ui32SysClock, pui8MACArray, 0, 0, 0, IPADDR_USE_DHCP);

    //
    // Setup the device locator service.
    //
    LocatorInit();
    LocatorMACAddrSet(pui8MACArray);
    LocatorAppTitleSet("EK-TM4C1294XL MQTT IO");

    //
    // Initialize a sample httpd server.
    //
    httpd_init();

    //
    // Set the interrupt priorities.  We set the SysTick interrupt to a higher
    // priority than the Ethernet interrupt to ensure that the file system
    // tick is processed if SysTick occurs while the Ethernet handler is being
    // processed.  This is very likely since all the TCP/IP and HTTP work is
    // done in the context of the Ethernet interrupt.
    //
    MAP_IntPrioritySet(INT_EMAC0, ETHERNET_INT_PRIORITY);
    MAP_IntPrioritySet(FAULT_SYSTICK, SYSTICK_INT_PRIORITY);

    //
    // Pass our tag information to the HTTP server.
    //
    http_set_ssi_handler((tSSIHandler)SSIHandler, g_pcConfigSSITags,
            NUM_CONFIG_SSI_TAGS);

    //
    // Pass our CGI handlers to the HTTP server.
    //
    http_set_cgi_handlers(g_psConfigCGIURIs, NUM_CONFIG_CGI_URIS);

    //
    // Initialize IO controls (legacy web-demo LED / animation timer).
    //
    io_init();

    //
    // Initialize the field-I/O chains with the configured device counts.  The
    // relay chain powers up with all relays off and outputs enabled.
    //
    DINChainInit(ConfigGetDinDevices());
    RelayChainInit(ConfigGetRelayDevices());
    UARTprintf("IO: %d input dev, %d relay dev.\n", ConfigGetDinDevices(),
               ConfigGetRelayDevices());

    //
    // Initialize the MQTT client subsystem (MAC seeds the HA device id).
    //
    MQTTAppInit(pui8MACArray);

    //
    // Wire the pushbutton click callback to the MQTT event publisher.
    //
    InputEventsSetCallback(IEClickCallback);

    //
    // Main loop.  Networking (lwIP, httpd, MQTT receive) runs in interrupt
    // context; here we service the periodic application tick: apply pending
    // (re)connect requests and drive the MQTT keep-alive/reconnect timers.
    //
    while(1)
    {
        //
        // If the OTA last-chunk handler requested a reset, wait one tick so
        // the HTTP response is delivered, then reset into the new firmware.
        //
        if(g_bOTAReset)
        {
            g_bOTAReset = false;
            MAP_SysCtlDelay(g_ui32SysClock / 3);  // ~333 ms — let TCP flush
            MAP_SysCtlReset();
        }

        //
        // Wait for the next SysTick (~10 ms) application tick.
        //
        while(!g_bSysTickFlag)
        {
        }
        g_bSysTickFlag = false;

        //
        // Apply a pending (re)connect request from DHCP completion or a web
        // configuration change.
        //
        if(g_bStartMQTT)
        {
            g_bStartMQTT = false;
            //
            // A config change may also have altered the device counts.  Only
            // reconfigure the relay chain when its count actually changed, so an
            // unrelated setting change does not switch the relays off.
            //
            DINChainSetDevices(ConfigGetDinDevices());
            if(RelayChainGetDevices() != ConfigGetRelayDevices())
            {
                RelayChainSetDevices(ConfigGetRelayDevices());
            }
            MQTTAppStart();
        }

        //
        // Re-publish HA discovery after an I/O configuration change (without
        // a full reconnect — the broker session stays live).
        //
        if(g_bRepublishMQTT)
        {
            g_bRepublishMQTT = false;
            MQTTAppRepublish();
        }

        //
        // Poll the input chain and the relay fault line; log any transitions.
        //
        DINChainScan();
        RelayFaultScan();

        //
        // Advance pushbutton click-detection timers.
        //
        InputEventsTick(SYSTICKMS);
        RelayPulseTick(SYSTICKMS);
        SntpTick(SYSTICKMS);

        //
        // Service MQTT keep-alive, reconnect timers and the post-connect
        // publish sequence.
        //
        MQTTAppTick(SYSTICKMS);
    }
}
