//*****************************************************************************
//
// board_pins.h (CC35x1) - LP-EM-CC35X1 pin map for the field-I/O chains.
//
// The portable din_chain.c / relay_chain.c bit-bang the SN65HVS882 input chain
// and DRV8860 relay chain through the pal_gpio primitives.  On this platform the
// TI Drivers GPIO API is index-based: the opaque (port, pin) pair carries the
// SysConfig CONFIG_GPIO_* index in 'pin' and ignores 'port' (see pal_gpio.c), so
// every *_PORT / *_PERIPH below is a don't-care 0 and every *_PIN is a
// CONFIG_GPIO_* index generated by SysConfig into ti_drivers_config.h.
//
// This mirrors mqtt_io/board_pins.h (the TM4C1294 map) symbol-for-symbol so the
// shared chain drivers compile unchanged; only the values differ.  The include
// search order (platform/cc35x1 ahead of mqtt_io) makes this file win over the
// TivaWare board_pins.h for the CC35x1 build.
//
// PIN ASSIGNMENTS ARE PROVISIONAL.  The LP-EM-CC35X1 on the bench is bare (no
// SN65HVS882 / DRV8860 add-on boards), so these are build-only placeholders
// routed to free BoosterPack pins: the input chain on the SPI0 header pins, the
// relay chain on the SPI1 header pins, and EN/nFAULT on the ADC header pins.
// They deliberately avoid the UART1 XDS110 backchannel (GPIO5/6), the RGB LED
// (GPIO30/34/35), the I2C sensors (GPIO10/11), and the buttons (GPIO2/36).
// Revisit once the I/O add-on hardware and its wiring are finalised.
//
//   Signal            SysConfig index        BoosterPack pin  Dir
//   ----------------  ---------------------  ---------------  ----
//   DIN  CLK          CONFIG_GPIO_DIN_CLK    GPIO27 (pin 7)   out
//   DIN  CE  (FSS)    CONFIG_GPIO_DIN_CE     GPIO26 (pin 18)  out
//   DIN  SOP (RX)     CONFIG_GPIO_DIN_SOP    GPIO28 (pin 14)  in
//   DIN  LD  (LATCH)  CONFIG_GPIO_DIN_LD     GPIO29 (pin 15)  out
//   REL  CLK          CONFIG_GPIO_REL_CLK    GPIO14 (pin 8)   out
//   REL  DIN (TX)     CONFIG_GPIO_REL_DIN    GPIO13 (pin 13)  out
//   REL  DOUT(RX)     CONFIG_GPIO_REL_DOUT   GPIO15 (pin 11)  in
//   REL  LATCH        CONFIG_GPIO_REL_LATCH  GPIO12 (pin 12)  out
//   REL  ENABLE       CONFIG_GPIO_REL_EN     GPIO3  (pin 26)  out
//   REL  nFAULT       CONFIG_GPIO_REL_NFAULT GPIO4  (pin 25)  in (pull-up)
//
//*****************************************************************************

#ifndef __BOARD_PINS_H__
#define __BOARD_PINS_H__

#include "ti_drivers_config.h"      // CONFIG_GPIO_* pin indices (SysConfig)

//*****************************************************************************
//
// Per-board channel counts (two 8-channel devices per board).
//
//*****************************************************************************
#define INPUTS_PER_BOARD        16      // 2x SN65HVS882
#define RELAYS_PER_BOARD        16      // 2x DRV8860

//*****************************************************************************
//
// Input chain - SN65HVS882 serializers (read-only), bit-banged.  'port' is
// unused on TI Drivers GPIO; 'pin' carries the CONFIG_GPIO_* index.
//
//   CLK -> CLK, CE -> clock enable (active-low), SOP <- serial data,
//   LD  -> load/latch (active-low).
//
//*****************************************************************************
#define INPUT_SSI_GPIO_PERIPH   0u      // no per-port clock gate on CC35x1
#define INPUT_LATCH_PERIPH      0u

#define INPUT_SSI_CLK_PORT      0u
#define INPUT_SSI_CLK_PIN       CONFIG_GPIO_DIN_CLK

#define INPUT_SSI_FSS_PORT      0u      // used as CE
#define INPUT_SSI_FSS_PIN       CONFIG_GPIO_DIN_CE

#define INPUT_SSI_RX_PORT       0u      // SOP
#define INPUT_SSI_RX_PIN        CONFIG_GPIO_DIN_SOP

#define INPUT_LATCH_PORT        0u      // LD (active-low)
#define INPUT_LATCH_PIN         CONFIG_GPIO_DIN_LD

//*****************************************************************************
//
// Output chain - DRV8860 relay drivers, bit-banged full-duplex.
//
//   CLK -> CLK, DIN -> relay data, DOUT <- fault/echo readback,
//   LATCH -> pulse after a full frame, ENABLE -> output enable,
//   nFAULT <- open-drain wired-OR fault (needs pull-up).
//
//*****************************************************************************
#define OUTPUT_SSI_CLK_PERIPH   0u
#define OUTPUT_SSI_E_PERIPH     0u
#define OUTPUT_ENABLE_PERIPH    0u

#define OUTPUT_SSI_CLK_PORT     0u
#define OUTPUT_SSI_CLK_PIN      CONFIG_GPIO_REL_CLK

#define OUTPUT_SSI_TX_PORT      0u      // DIN
#define OUTPUT_SSI_TX_PIN       CONFIG_GPIO_REL_DIN

#define OUTPUT_SSI_RX_PORT      0u      // DOUT
#define OUTPUT_SSI_RX_PIN       CONFIG_GPIO_REL_DOUT

#define OUTPUT_LATCH_PORT       0u
#define OUTPUT_LATCH_PIN        CONFIG_GPIO_REL_LATCH

#define OUTPUT_ENABLE_PORT      0u
#define OUTPUT_ENABLE_PIN       CONFIG_GPIO_REL_EN

#define OUTPUT_NFAULT_PORT      0u      // input, needs pull-up
#define OUTPUT_NFAULT_PIN       CONFIG_GPIO_REL_NFAULT

#endif // __BOARD_PINS_H__
