#!/usr/bin/env python3
# -----------------------------------------------------------------------------
# makefsdata.py - generate an lwIP 2.x apps/httpd fsdata.c from a web root.
#
# The SDK ships two makefsdata variants and neither is usable here as-is: the
# extensionless Perl script emits a legacy 4-field fsdata_file initializer (no
# `flags`), which is incompatible with this SDK's lwip-stack fs.h/httpd.c
# (5-field, flags-driven header handling); the C tool needs a host compiler we
# do not have on this Windows box.  This script reproduces the *reference*
# fsdata.c format (source/third_party/lwip/.../apps/http/fsdata.c) exactly:
#
#   struct fsdata_file { next; name; data; len; flags; };
#
# with the file's HTTP response header baked in (FS_FILE_FLAGS_HEADER_INCLUDED)
# and the null-terminated name padded to a 4-byte boundary ahead of the data.
#
# SSI note: for SSI extensions (.shtml/.shtm/.ssi/.xml/.json) we deliberately
# OMIT Content-Length from the baked header, because the SSI tag substitution
# httpd performs at serve time changes the body length; a fixed Content-Length
# would truncate the response.  Such files are served HTTP/1.0 connection-close
# (FS_FILE_FLAGS_HEADER_INCLUDED, not PERSISTENT).
#
# Usage:  python makefsdata.py <web_root_dir> -o <output.c>
# -----------------------------------------------------------------------------
import argparse
import os
import sys

SSI_EXTS = {".shtml", ".shtm", ".ssi", ".xml", ".json"}

CONTENT_TYPES = {
    ".html": "text/html", ".shtml": "text/html", ".shtm": "text/html",
    ".htm": "text/html", ".css": "text/css", ".js": "application/javascript",
    ".json": "application/json", ".xml": "text/xml", ".gif": "image/gif",
    ".png": "image/png", ".jpg": "image/jpeg", ".jpeg": "image/jpeg",
    ".ico": "image/x-icon", ".svg": "image/svg+xml", ".txt": "text/plain",
}

SERVER = "lwIP/2.1.3 (CC35x1 MQTT-IO)"


def mangle(path):
    return path.replace("/", "_").replace(".", "_").replace("-", "_")


def fmt_bytes(data):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("".join("0x%02x," % b for b in chunk))
    return "\n".join(lines)


def build_file(path, content):
    ext = os.path.splitext(path)[1].lower()
    is_ssi = ext in SSI_EXTS
    ctype = CONTENT_TYPES.get(ext, "text/plain")

    status = "404 File not found" if "404" in path else "200 OK"
    hdr = "HTTP/1.0 %s\r\n" % status
    hdr += "Server: %s\r\n" % SERVER
    hdr += "Content-type: %s\r\n" % ctype
    if not is_ssi:
        hdr += "Content-Length: %d\r\n" % len(content)
    hdr += "\r\n"
    hdr = hdr.encode("ascii")

    name = path.encode("ascii") + b"\x00"
    padlen = (len(name) + 3) & ~3
    name = name + b"\x00" * (padlen - len(name))

    flags = "FS_FILE_FLAGS_HEADER_INCLUDED"
    if not is_ssi:
        flags += " | FS_FILE_FLAGS_HEADER_PERSISTENT"

    return name, hdr, content, len(name), flags


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("root")
    ap.add_argument("-o", "--output", default="fsdata.c")
    args = ap.parse_args()

    #
    # Hard guard: this generator emits CC35x1 (lwIP 2.x) nomenclature - it opens
    # the file with `#include "lwip/apps/fs.h"`, which does NOT exist under
    # TivaWare's lwip-1.4.1.  The TM4C web FS (mqtt_io/io_fsdata.h) is a separate,
    # hand-maintained lwip-1.4.1 file generated by TivaWare's makefsfile.exe.  A
    # past regression pointed this tool's -o at io_fsdata.h and cross-contaminated
    # it, breaking the TM4C build.  Refuse that output outright so it cannot recur.
    #
    if os.path.basename(args.output).lower() == "io_fsdata.h":
        sys.exit("refusing to write TM4C io_fsdata.h with the CC35x1 generator; "
                 "regenerate it with TivaWare makefsfile.exe (lwip-1.4.1) instead")

    files = []
    for dirpath, _, names in os.walk(args.root):
        for n in sorted(names):
            full = os.path.join(dirpath, n)
            rel = os.path.relpath(full, args.root).replace(os.sep, "/")
            files.append(("/" + rel, full))
    files.sort()
    if not files:
        sys.exit("no files found under %s" % args.root)

    out = []
    out.append("/* Generated by platform/cc35x1/tools/makefsdata.py - do not edit. */")
    out.append('#include "lwip/apps/fs.h"')
    out.append('#include "lwip/def.h"')
    out.append("")
    out.append("#define file_NULL (struct fsdata_file *) NULL")
    out.append("")
    out.append("#ifndef FS_FILE_FLAGS_HEADER_INCLUDED")
    out.append("#define FS_FILE_FLAGS_HEADER_INCLUDED 1")
    out.append("#endif")
    out.append("#ifndef FS_FILE_FLAGS_HEADER_PERSISTENT")
    out.append("#define FS_FILE_FLAGS_HEADER_PERSISTENT 0")
    out.append("#endif")
    out.append("")

    entries = []
    for path, full in files:
        with open(full, "rb") as f:
            content = f.read()
        name, hdr, content, namelen, flags = build_file(path, content)
        var = mangle(path)
        blob = name + hdr + content
        out.append("static const unsigned char data%s[] = {" % var)
        out.append("/* %s (%d chars) */" % (path, len(path)))
        out.append(fmt_bytes(name))
        out.append("/* HTTP header */")
        out.append(fmt_bytes(hdr))
        out.append("/* raw file data (%d bytes) */" % len(content))
        out.append(fmt_bytes(content))
        out.append("};")
        out.append("")
        entries.append((var, namelen, flags))

    prev = "file_NULL"
    for var, namelen, flags in entries:
        out.append("const struct fsdata_file file%s[] = { {" % var)
        out.append("%s," % prev)
        out.append("data%s," % var)
        out.append("data%s + %d," % (var, namelen))
        out.append("sizeof(data%s) - %d," % (var, namelen))
        out.append("%s," % flags)
        out.append("} };")
        out.append("")
        prev = "file%s" % var

    out.append("#define FS_ROOT %s" % prev)
    out.append("#define FS_NUMFILES %d" % len(entries))
    out.append("")

    with open(args.output, "w", newline="\n") as f:
        f.write("\n".join(out))
    print("wrote %s (%d files)" % (args.output, len(entries)))


if __name__ == "__main__":
    main()
